### PR TITLE
ENH: downloads badge

### PR DESCRIPTION
**Pull request by jasmainak**
Tiny tweak to readme since we have package on pip now

### CODE REVIEW

**Comment by sappelhoff** [comment]
+1, but https://github.com/mne-tools/mne-python/pull/5695 introduced an import error on our side (the downsides of using MNE master) ... can you make a quickfix in this PR as well?

**Comment by jasmainak** [comment]
The quickfix is in PR #129 :-)

**Comment by sappelhoff** [comment]
okay, let's merge then

**Comment by sappelhoff** [comment]
thanks Mainak!

**Pull request merged**
