### PR TITLE
WIP: Try using bids_path

### LINKED ISSUE #255: make_bids_basename -> BIDSPath ?
Reading the code in mne-study-template I had the feeling that `make_bids_basename` is overused. For example, here:

https://github.com/mne-tools/mne-study-template/blob/master/01-import_and_filter.py#L58

I think some of this would be simplified if we make a thin class that inherits from a dictionary and has a `property` attribute that returns the string. So, something like:

```py
>>> bids_path = BIDSPath(subject=subject, session=session, task=config.task, acq=config.acq,
                         processing=config.proc, recording=config.rec,  space=config.space)
>>> bids_path[run] = run
>>> bids_path.name # gives the string representation
```

also within `mne-bids` a ton of code could be simplified like here: https://github.com/mne-tools/mne-bids/blob/master/mne_bids/write.py#L840-L859

what do you guys think @agramfort @sappelhoff ?

### PR DESCRIPTION
**Pull request by jasmainak**
closes #255 

PR Description
--------------
Just a quick draft to see how it looks with BIDSPath

I'll continue later as I've meeting with Matti now

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"
- [ ] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by sappelhoff** [comment]
I think I like the idea. It would also help us with getting rid of funky code like these lines: https://github.com/mne-tools/mne-bids/blob/f8f267b45ac36e1600ea9ceb5540299e1bf3ab21/mne_bids/tests/test_write.py#L153

... which are not all too rare.

But I would probably rather push this to 0.4, so we have more time to try and experiment and streamline

**Comment by adam2392** [comment]
@jasmainak just wondering what are the lacking parts you think to get this working?

**Comment by jasmainak** [comment]
umm ... I think the first job is to show it can help reduce the number of lines of code = lots of red lines in the codebase (this will help convince @agramfort). Then to update the tests to make it work. Unfortunately, I didn't push it much. 

Just a couple of ideas if you want to give this a shot:
- I think the changes should not be as invasive as in this PR. Maybe `make_bids_filename` return an instance of `BIDSPath` instead of having the user call the class directly
- Instead of having a `name` property method, it might make sense to have a `__repr__`. I'm not too sure of this as it might confuse users and they would think it's a string when it's not.

Maybe @hoechenberger or @agramfort might have some opinions already, so it would be good to discuss a bit before trying to wasting too much effort / time.

**Comment by agramfort** [comment]
@jasmainak knows me well :) show me that user code becomes nicer and simpler
and I will be convinced.

>

**Comment by adam2392** [comment]
> umm ... I think the first job is to show it can help reduce the number of lines of code = lots of red lines in the codebase (this will help convince @agramfort). Then to update the tests to make it work. Unfortunately, I didn't push it much.

I will (try to) attempt something like this because my code  gets very cluttered with passing around subject, session, task, run, acquisition, etc. across functions rather then just a `bids_basename`, which can be altered on the fly. 

The thing is... idk if mne-bids has a lot of this in the code/tests? But I'll check.

> * I think the changes should not be as invasive as in this PR. Maybe `make_bids_filename` return an instance of `BIDSPath` instead of having the user call the class directly

Fair, and allow `make_bids_filename` to gain traction before subbing it into `make_bids_basename`?

> * Instead of having a `name` property method, it might make sense to have a `__repr__`. I'm not too sure of this as it might confuse users and they would think it's a string when it's not.

Perhaps `__repr__` outputs: `<BIDS Path> sub-01_ses-01_run-01.edf` or something like?

**Pull request closed without merging**
