### PR TITLE
MAINT: Tolerate new MNE behavior

### PR DESCRIPTION
**Pull request by larsoner**
@hoechenberger should fix the failing test following https://github.com/mne-tools/mne-python/pull/11212 where fiducials are estimated and added when implicitly converting to the head coordinate frame

### CODE REVIEW

**Comment by larsoner** [comment]
I also just pushed a commit to avoid using `importlib_resources`. It's causing a conda-forge build error:

https://github.com/conda-forge/mne-bids-feedstock/pull/21

Keeping it would mean 1) adding to setup.py deps, probably dependent on Python version, 2) changing the import, probably with a try/except, 3) updating the feedstock. What I've implemented here instead is just `data_dir = Path(__file__).parent / 'data'` which requires none of these gymnastics, and hopefully is good enough.

**Comment by hoechenberger** [comment]
Sounds good to me. Some tests are still failing though!

**Comment by larsoner** [comment]
Those should be fixed by https://github.com/mne-tools/mne-python/pull/11230

**Comment by larsoner** [comment]
Ready for review/merge from my end

**Review by sappelhoff — APPROVED** [review]

**Comment by sappelhoff** [comment]
Thanks @larsoner

**Comment by sappelhoff** [comment]
we should probably have removed this line as well with this PR, right?

https://github.com/mne-tools/mne-bids/blob/ee27b43acd7fede44a384fe5762f90c70a460789/setup.cfg#L41

**Comment by larsoner** [comment]
Yes we should have, thanks @sappelhoff !

**Pull request merged**
