### PR TITLE
Move emojis in issue templates to the titles

### PR DESCRIPTION
**Pull request by hoechenberger**
Followup to #1056

I think it has a much better effect this way!

Merge checklist
---------------

Maintainer, please confirm the following before merging.
If applicable:

- [ ] All comments are resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] New contributors have been added to [CITATION.cff](https://github.com/mne-tools/mne-bids/blob/main/CITATION.cff)
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by hoechenberger** [comment]
@sappelhoff WDYT?

https://github.com/mne-tools/mne-bids/issues/new/choose

Screen Shot 2022-08-27 at 10 39 34

**Comment by hoechenberger** [comment]
@sappelhoff Can we change the order of the items? I'd like to put the forum first, followed by feature request, bug report, and BIDS spec. Just so as to emphasize that users should probably ask on the forum before opening an issue here

**Comment by sappelhoff** [comment]
Looks better, thanks!

No idea about the order. Perhaps in the config yml?

**Comment by hoechenberger** [comment]
It's not urgent, was just an idea :)

**Comment by drammock** [comment]
IIRC you can't make the forum link come before the entries that are actual issue templates. I looked into it a few months ago because I had the same instinct that it would be better to have that at the top

**Pull request merged**
