### PR TITLE
[MRG] Remove _estimate_line_freq

### PR DESCRIPTION
**Pull request by alexrockhill**
Followup to #503.

Describe your PR here

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [x] All comments resolved
- [x] This is not your own PR
- [ ] All CIs are happy
- [x] PR title starts with [MRG]
- [x] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"
- [ ] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by agramfort** [comment]
@mne-tools/mne-bids-contributors apparently validator requires PowerLineFrequency to be specified. It cannot be 'n/a'

any opinion on this ?

2 options:
- make it optional in standard/validator
- prevent people from writing bids files without specifying (at worse manually) the PowerLineFrequency

**Comment by jasmainak** [comment]
Option 2 makes more sense. To check while writing.

**Comment by agramfort** [comment]
ok I'll go with 2 here... doing it now

**Comment by hoechenberger** [comment]
Thanks, @alexrockhill and @agramfort!

**Pull request merged**
