### PR TITLE
[MRG] DOC clarify manufacturer field

### LINKED ISSUE #277: BIDS converter uses extension name to determine manufacturer, which is not always true
I have some files that were converted from KIT to FIF. I would like to set up my folders/files in BIDS but I noticed that the original manufacturer information is falling back to Elekta instead of KIT. I think this would be a problem with any system that was using MNE that read in their original source files but were saved to FIF. Is there a way to get the original manufacturer information from the FIF file or would this be a manual step for the user. If so, we should document that somewhere.

### PR DESCRIPTION
**Pull request by jasmainak**
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-bids/blob/master/CONTRIBUTING.md)

PR Description
--------------

clarify how the manufacturer field is generated

closes #277 

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"
- [ ] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by jasmainak** [comment]
@alexrockhill you might want to review this PR

**Comment by teonbrooks** [comment]
this looks good. just thinking, should we have it in the documentation as well, not just the example?

**Comment by jasmainak** [comment]
> should we have it in the documentation as well, not just the example?

what do you have in mind? What part of the documentation should this go in?

**Comment by teonbrooks** [comment]
I would add it as a warning in the `write_raw_bids` like we have the one about simply copying over files.
https://mne.tools/mne-bids/generated/mne_bids.write_raw_bids.html#mne_bids.write_raw_bids

**Comment by jasmainak** [comment]
humm but we already have a warning there.

**Comment by teonbrooks** [comment]
> humm but we already have a warning there.

it's a warning about modification. if you were using mne with a non-Elekta system, your data were stored in FIF and the manufacturer will be incorrect. this caveat should be bundled into the message.

**Comment by teonbrooks** [comment]
great. looks like you need to rebase

**Comment by jasmainak** [comment]
Rebased.

**Comment by teonbrooks** [comment]
thx @jasmainak

**Pull request merged**
