### PR TITLE
[MRG] Ensure examples don't repurpose "dirty" BIDS root

### LINKED ISSUE #640: sphinx-gallery examples are not run in "clean" environment on Circle
Checking out [example 2](https://mne.tools/mne-bids/dev/auto_examples/convert_mne_sample.html#sphx-glr-auto-examples-convert-mne-sample-py), which demonstrated how `sample` can be converted to BIDS, I realized we only touch MEG data of the `sample` subject, nothing else. 

Yet, `print_dir_tree` reveals MR and empty room data in the BIDS dir, which shouldn't be there – they must be leftovers from a previous test:

Screen Shot 2020-11-24 at 20 08 37

This can be very confusing.

### PR DESCRIPTION
**Pull request by hoechenberger**
PR Description
--------------

We now delete the output folders before proceeding, and I've added a
warning to the notebooks about this deletion.

Also make things more consistent across examples.

Fixes #640

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by hoechenberger** [comment]
Example 2 in master:



this PR:
Screen Shot 2020-11-27 at 12 07 31

**Review by sappelhoff — APPROVED** [review]
great! thanks

**Review by agramfort — APPROVED** [review]
it's ok for me but I let @sappelhoff and @jasmainak voice their concerns if any

**Comment by agramfort** [comment]
actually @sappelhoff if ok !

**Comment by jasmainak** [comment]
Looks nice to me! mne-bids gets better with every PR :)

**Pull request merged**
