### PR TITLE
[MRG] _return_root_paths now only looks in subfolders of root starting with 'sub-'

### LINKED ISSUE #1127: restrict `find_matching_paths` to only look outside of `derivatives/`
### Description of the problem

This command is supposed to find 4 .set files for the given subject, from 4 different subjects:

`setFilePaths = mb.find_matching_paths(root=root,extensions='.set',datatypes='eeg')
`
However, it finds 8. Inspecting these 8, it turns out that 4 of them are 'bastard-files' with directories matching the subejct/session directories of the correct files, but basenames matching .set files in a derivatives folder. Looking in path.py, it seems that `fpaths = _return_root_paths(root, datatype=datatypes, ignore_json=False)` looks in all subfolders beneath root, including 'derivatives', after which `_filter_fnames` does not check whether anything has been collected accidentally. Finally, `_fnames_to_bidspaths` creates bidspaths using the inferred subject/session folder based on the basename, but with root specifically set to the root command passed to `find_matching_paths which leads to these 'bastard' bidspaths. 

### Steps to reproduce

search for bidsfiles in a root directory which also contains a derivatives folder with similar bids-formatted files inside.

### Expected results

I suggest ensuring that "find_matching_paths" ignores 'sourcedata' and 'derivatives' when walking the folder tree. 

### Actual results

find_matching_paths returns too many bidspaths. 

### Additional information

I don't remember whether the BIDS standard requires subject folders be called 'sub-X', if so, it would be easy to only search folders matching that pattern. Otherwise, 'derivatives', 'sourcedata', 'code' and 'stimuli' might be good folders to ignore when searching for matching files.

### PR DESCRIPTION
**Pull request by kaare-mikkelsen**
PR Description
--------------

In relation to this issue: https://github.com/mne-tools/mne-bids/issues/1127

I now submit this pull request. It's a pretty simple solution - after calling root.rglob(pattern), returned paths are filtered such that only those starting with root / 'sub-' are sent on. 

This closes #1127

Merge checklist
---------------

Maintainer, please confirm the following before merging.
If applicable:

- [ ] All comments are resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] New contributors have been added to [CITATION.cff](https://github.com/mne-tools/mne-bids/blob/main/CITATION.cff)
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by kaare-mikkelsen** [comment]
so, I can see that my commit fails a lot of tests, despite being a very minor change? besides changing the length of line 2444 to be compatible with the style guide, what else should I do?

**Comment by sappelhoff** [comment]
@kaare-mikkelsen there were some unrelated failures that should now be fixed in main. I have merged these changes into your branch -- let's see how the CI comes back.

**Comment by hoechenberger** [comment]
@sappelhoff We should probably set up the autofix.ci bot to make contributors' lives easier

**Comment by sappelhoff** [comment]
@kaare-mikkelsen I plan to have a look at this within the next three weeks -- thanks for your patience!

**Comment by sappelhoff** [comment]
please see #1281, which replaces this PR.

**Pull request closed without merging**
