### PR TITLE
[MRG] remove mpl as a general dependency.

### LINKED ISSUE #158: Removing MATPLOTLIB dependency
After #122 is merged, we should remove MATPLOTLIB

1. from our documented dependencies
2. from the CIs
3. add it as a "doc dependency"
4. add it to circleCI for building the docs

### PR DESCRIPTION
**Pull request by sappelhoff**
PR Description
--------------

fixes #158 

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [x] All comments resolved
- [x] This is not your own PR
- [x] All CIs are happy
- [x] PR title starts with [MRG]
- [x] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [x] PR description includes phrase "closes <#issue-number>"
- [x] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by sappelhoff** [comment]
Mmh AppVeyor complains but not due to the MPL removal ... pytest-cov seems to be the culprit here.

It seems to me that we need a higher pytest version than the 3.3.2 we require ... why don't we use the most recent pytest? Was that a python2 / python3 decision? @jasmainak @monkeyman192

**Comment by jasmainak** [comment]
umm ... I am not sure. Okay to upgrade pytest if that makes it work

**Comment by sappelhoff** [comment]
it's strange though that Travis passes ...

**Comment by sappelhoff** [comment]
@jasmainak using the most recent release of pytest fixed the appveyor problem and did not create problem with the other CIs :-)

ready to have this minor contribution merged.

**Comment by jasmainak** [comment]
Merged. Thanks @sappelhoff !

**Pull request merged**
