### PR TITLE
TESTS: Try to fix CI

### PR DESCRIPTION
**Pull request by hoechenberger**
PR Description
--------------

pytest-sugar currently doesn't support pytest 5.4, see https://github.com/Teemu/pytest-sugar/issues/187

Pinning pytest to <5.4 for now to hopefully make CIs work again.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"
- [ ] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
@hoechenberger maybe `doc/environment.yml` needs to be updated too?

https://github.com/mne-tools/mne-bids/blob/71520d6b0cd3907393173a663e064050be1b8012/doc/environment.yml#L20

<details>

```
#!/bin/bash -eo pipefail
diff <(grep -v '^  - mne_bids~=0.3$' doc/environment.yml) <(cat environment.yml)

19c19
<   - pytest
---
>   - pytest<5.4

Exited with code exit status 1

CircleCI received exit code 1
```

</details>

**Comment by sappelhoff** [comment]
Thanks @hoechenberger! Travis fails because it wants you to keep `environment.yml` and `doc/environment.yml` in sync ... so adding the pytest change there will fix travis (at least that single check)

**Comment by hoechenberger** [comment]
Thanks @sappelhoff and @GuillaumeFavelier

**Comment by agramfort** [comment]
we should migrate CIs from appveyor to azure pipelines as it's much faster for windows

any objection?

**Comment by hoechenberger** [comment]
> we should migrate CIs from appveyor to azure pipelines as it's much faster for windows
> 
> any objection?

None from my side, but I've never created an Azure pipeline before, so would need a little time to get this to work. Or sb else would have to do it :)

**Comment by sappelhoff** [comment]
No objection, but perhaps it can be done the next time we have issues with the CIs ... currently it's working so we can just leave it as they are?

**Comment by agramfort** [comment]
it's working but it slows down feedback on PRs

to be done when someone needs to procrastinate

**Comment by agramfort** [comment]
thx @hoechenberger

**Comment by sappelhoff** [comment]
@agramfort @hoechenberger .. coming back to the CI discussion and moving Appveyor --> Azure Pipelines.

It might be possible that we can test Linux, MacOS, and Windows all using GitHub Actions (https://github.com/features/actions)

image


Just to keep in mind.

Maybe @larsoner knows more about this?

**Comment by agramfort** [comment]
I hear good things about github actions but never played with it

>

**Comment by larsoner** [comment]
Yes you can probably go either way. I have limited direct experience with GitHub actions. It does [seem to have some annoying limitations](https://github.com/sphinx-gallery/sample-project/pull/8#issuecomment-594551232). My guess is that Azure will be easier because there are many existing repos using it that you could use to build up an appropriate `azure-pipelines.yml`.

**Comment by agramfort** [comment]
I would keep circle for the doc. Just get it of appveyor which is too slow

>

**Comment by jasmainak** [comment]
I would stay away from github actions for now. Not sure how mature it is ...

**Pull request merged**
