### PR TITLE
MRG: Use explicitly public namespaces

### PR DESCRIPTION
**Pull request by larsoner**
In https://github.com/mne-tools/mne-python/pull/11903 we're trying to make some mne/io stuff private. This changes mne-bids to use the explicitly public API

### CODE REVIEW

**Comment by sappelhoff** [comment]
@larsoner maybe of interest to you: https://github.com/sappelhoff/mne-bids/actions/runs/5946959859/job/16128317716 (CI failure)

**Comment by drammock** [comment]
> @larsoner maybe of interest to you: https://github.com/sappelhoff/mne-bids/actions/runs/5946959859/job/16128317716 (CI failure)

The error on that CI run seems to not have the changes in this PR?

https://github.com/sappelhoff/mne-bids/actions/runs/5946959859/job/16128317716#step:16:60

still says
```py
from mne.io.pick import pick_types
```

**Comment by larsoner** [comment]
Indeed that's a run on the `sappelhoff` fork:

https://github.com/sappelhoff/mne-bids/blame/1a195dc975ab8cc095957d5ea0a4243fa03c9498/mne_bids/utils.py#L19

You need to update your `main`. Things are okay on `mne-tools/mne-bids`:

https://github.com/mne-tools/mne-bids/blame/b5fb3037f130521a4ef889feafba5f7a16e548f0/mne_bids/utils.py#L19

**Comment by sappelhoff** [comment]
sorry for the noise and thanks for the explanation.

**Pull request merged**
