### PR TITLE
[MRG] FIX: check meas_date=None with CTF data

### PR DESCRIPTION
**Pull request by jasmainak**
PR Description
--------------

Hopefully this will bring the CIs back to green.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [x] All CIs are happy
- [x] PR title starts with [MRG]
<s>- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated</s>
<s>- [ ] PR description includes phrase "closes <#issue-number>"</s>
- [x] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by jasmainak** [comment]
@alexrockhill and @bloyl would you mind taking a look?

**Comment by bloyl** [comment]
I guess I don't understand the point of the test at this point.

If the purpose is to test if `get_anonymization_daysback` raises a `ValueError` when `meas_date==None` I would remove the test from the `test_ctf` since it doesn't have anything to do with ctf data and put it in `test_get_anonymization_daysback():`

**Comment by bloyl** [comment]
There was a bug in mne-python where the `meas_date` was never set when reading ctf data.
this was addressed with this PR https://github.com/mne-tools/mne-python/pull/7104.

I'm assuming you are testing against `mne-python:master` so when that was merged the test started to fail?

**Comment by alexrockhill** [comment]
Sorry to be too late but looks good

**Pull request merged**
