### PR TITLE
[MRG] MAINT: use setup.cfg feature to get version

### PR DESCRIPTION
**Pull request by sappelhoff**
a nice and small enhancement I think

I am using that in `eeg_positions` and it worked like a charm: https://github.com/sappelhoff/eeg_positions/blob/master/setup.cfg

### CODE REVIEW

**Review by agramfort — COMMENTED** [review]
LGTM provided CIs are green

**Comment by sappelhoff** [comment]
I got weird CI issues on Linux, gonna check whether that was related to the changes.

**Comment by sappelhoff** [comment]
> I got weird CI issues on Linux, gonna check whether that was related to the changes.

okay, these issues are not related to my changes: https://github.com/mne-tools/mne-bids/runs/2148925065

Other PRs will most likely start running into these soon. :man_shrugging:

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Thanks @sappelhoff

**Pull request merged**
