### PR TITLE
add task entity to cal and ct fpath

### PR DESCRIPTION
**Pull request by dnacombo**
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-bids/blob/main/CONTRIBUTING.md)

PR Description
--------------

add task entity in calibration and cosstalk fpath property of BIDSpath.
todo: also add run and other entities?

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by hoechenberger** [comment]
Thanks @dnacombo! This does make sense to me at the first glance, I'm surprised tests are failing though 🤔 I'll probably have a chance to look into this later today!

**Comment by dnacombo** [comment]
Keep getting reminders that it fails. No idea how to fix this. @hoechenberger

**Comment by hoechenberger** [comment]
Whoops, totally forgot about this. Not sure about those reminders too, this sounds annoying!

I'll have a look at this today.

**Comment by hoechenberger** [comment]
Hello @dnacombo, I just had a look at the [BIDS specification](https://bids-specification.readthedocs.io/en/stable/99-appendices/06-meg-file-formats.html#cross-talk-and-fine-calibration-files) again, and it appears that `task` can currently not be included in the cross-talk and fine-calibration filenames.

Is there a specific use case you're seeing where having the `task` included would make sense? Normally, I'd expect calibration and crosstalk not to change within a single session..?

**Comment by dnacombo** [comment]
Ok, that makes sense, of course. So I'll rename my files.Thanks

**Comment by hoechenberger** [comment]
You're welcome! If you delete this branch from your GitHub repo, you will also get rid of those annoying messages from the CI service

**Pull request closed without merging**
