### PR TITLE
[BUG] Fix matplotlib version issues for 3.4.0 release

### PR DESCRIPTION
**Pull request by alexrockhill**
Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by hoechenberger** [comment]
Same CI problem, same issue with mne-python too

**Comment by hoechenberger** [comment]
ok seems to be back to normal now. canceled like 3 dozen pending workflows.

**Comment by hoechenberger** [comment]
It stalled again, so I canceled it :S

**Comment by hoechenberger** [comment]
Let's try this again once #760 has been merged

**Comment by alexrockhill** [comment]
Thanks @hoechenberger, sorry I made such a mess of this, I was trying to fix it :(

**Comment by hoechenberger** [comment]
It's not your fault, we misconfigured GH Actions 😊

**Comment by hoechenberger** [comment]
It appears this is stalled again, @alexrockhill … maybe @drammock has an idea on what's going on?

**Comment by alexrockhill** [comment]
> It appears this is stalled again, @alexrockhill … maybe @drammock has an idea on what's going on?

Huh, I just ran the tests locally and they didn't hang up...

**Comment by hoechenberger** [comment]
At least the auto-cancellation after 60 min, which I added in #760, seems to be doing its job :)

**Comment by alexrockhill** [comment]
Oh maybe it's still hanging up, I have a meeting but I'll fix it after. I just did all the tests and it hung up...

**Comment by alexrockhill** [comment]
Gosh that was a total rookie move, I was modifying the object I was looping over and didn't copy so that it didn't complete the loop and remove all the child figures and then that caused the parent to hang when it tried to remove all the child figures with the non-functioning `close(fig)` method.

**Comment by alexrockhill** [comment]
Huh, all those tests pass locally, not sure what's wrong now

**Comment by drammock** [comment]
@alexrockhill I can get the MNE-Python tests to fail locally if I set `MNE_BROWSE_RAW_SIZE` to `'6.4,4.8'` which is the default size when it's never been changed by the user.  I've isolated which MPL commit first fails, and am working on figuring out why exactly that particular change causes the fail.

**Comment by drammock** [comment]
hopefully https://github.com/mne-tools/mne-python/pull/9217 will work 🤞🏻

**Comment by alexrockhill** [comment]
Huh, it worked with mne-python version 0.22 locally for this test, not sure if that has to do with the PR but hopefully that fixes things

**Comment by alexrockhill** [comment]
If the double click was the issue then the main tests should pass and the stable should fail ASAIK

**Comment by alexrockhill** [comment]
Well I am just perplexed, `ubuntu-latest` passes but everything else fails that just doesn't make sense

**Comment by alexrockhill** [comment]
> Well I am just perplexed, `ubuntu-latest` passes but everything else fails that just doesn't make sense

Oh wait looking at the workflow that's just because `ubuntu-latest` is the only one that clones the `main` branch of `mne-python` everything else clones the `maint/0.22`. So solved, thanks @drammock!

**Comment by alexrockhill** [comment]
So then the `mne-bids` dependency should be left as mpl<3.4 until the next `mne-python` release so we should wait until then to merge this PR I guess

**Comment by alexrockhill** [comment]
So now that the new stable version of mne is released, I think this should be good to merge after retriggering tests

**Comment by hoechenberger** [comment]
Can you pull in `main` to see if this fixes the tests?

**Comment by alexrockhill** [comment]
> Can you pull in `main` to see if this fixes the tests?

Hmmm, I rebased but this is using the latest stable version of mne-python (0.22.1) so I thought this would work... I'll have to think about what the issue is.

**Comment by alexrockhill** [comment]
I guess since `main` works we could just wait until the next full version is released...

**Comment by sappelhoff** [comment]
@alexrockhill @hoechenberger was this issue resolved somewhere upstream and this PR is now obsolete? CIs seem to pass on main without the tweaks here.

**Pull request closed without merging**
