### PR TITLE
Move make_bids_basename() heavy-lifting to a new private function, and raise by default if the users wants to create an "invalid" (violating the SHOULD) empty-room basename

### PR DESCRIPTION
**Pull request by hoechenberger**
PR Description
--------------

This new private function allows us to generate certain basenames for empty-room recordings that would otherwise be considered invalid and raise an exception. It features two new kwargs to control the behavior: `on_invalid_er_session` and `on_invalid_er_task`. By default, we raise exceptions if we encounter values not conforming to the BIDS "SHOULD" directions. These parameters are **not** exposed through the public API.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [x] All comments resolved
- [x] This is not your own PR
- [x] All CIs are happy
- [x] PR title starts with [MRG]
- [x] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [x] PR description includes phrase "closes <#issue-number>"
- [x] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by hoechenberger** [comment]
I see tests don't cover the private function fully (the cases where it's supposed to raise and warn), let me know if I should add test cases:

https://codecov.io/gh/mne-tools/mne-bids/pull/427/diff?src=pr&el=tree#diff-bW5lX2JpZHMvdXRpbHMucHk=

**Comment by jasmainak** [comment]
@hoechenberger looks like you have a conflict

**Comment by hoechenberger** [comment]
@jasmainak rebased on master & resolved

**Comment by agramfort** [comment]
you have a related travis failure @hoechenberger

**Comment by hoechenberger** [comment]
Good catch @agramfort, hope it's fixed now

**Pull request merged**
