### PR TITLE
[BUG] Fix matplotlib for version 3.4

### PR DESCRIPTION
**Pull request by alexrockhill**
PR Description
--------------

Fix failing tests due to matplotlib upgrade.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [x] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by alexrockhill** [comment]
Fixed 4/8!

**Comment by alexrockhill** [comment]
Not able to replicate the others so starting with a new environment and following the CI process locally, might take a bit

**Comment by alexrockhill** [comment]
Ok I installed a new environment and checked that I have all the same versions but I'm not able to reproduce the failed tests... anyone have a minute to help?

**Comment by alexrockhill** [comment]
So after some inspection, it appears that `mne.utils._testing._click_ch_name` isn't working, i.e. the channel is not clicked as bad which doesn't trigger the save/discard dialog box

**Comment by sappelhoff** [comment]
>Ok I installed a new environment and checked that I have all the same versions but I'm not able to reproduce the failed tests... anyone have a minute to help?

just ran `make` on an up to date local `main` branch, and everything passed

click details for output of `conda list`:

<details>
see:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
alabaster                 0.7.12                   pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
babel                     2.9.0                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                         mkl  
build                     0.3.0                    pypi_0    pypi
ca-certificates           2021.1.19            h06a4308_1  
certifi                   2020.12.5        py38h06a4308_0  
chardet                   4.0.0                    pypi_0    pypi
check-manifest            0.46                     pypi_0    pypi
coverage                  5.5                      pypi_0    pypi
cycler                    0.10.0                   py38_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2              pyhd3eb1b0_0  
docutils                  0.16                     pypi_0    pypi
expat                     2.2.10               he6710b0_2  
flake8                    3.8.4                    pypi_0    pypi
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
glib                      2.67.4               h36276a3_1  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
icu                       58.2                 he6710b0_3  
idna                      2.10                     pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2020.2                      254  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.21.0           py38hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
jedi                      0.17.0                   py38_0  
jinja2                    2.11.3                   pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
jupyter_client            6.1.7                      py_0  
jupyter_core              4.7.1            py38h06a4308_0  
kiwisolver                1.3.1            py38h2531618_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.3                h2531618_0  
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.4            py38h06a4308_0  
matplotlib-base           3.3.4            py38h62a2d02_0  
mccabe                    0.6.1                    pypi_0    pypi
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.3.0            py38h54f3939_0  
mkl_random                1.1.1            py38h0573a6f_0  
mne                       0.23.dev0                 dev_0    <develop>
mne-bids                  0.8.dev0                  dev_0    <develop>
ncurses                   6.2                  he6710b0_1  
nibabel                   3.2.1                    pypi_0    pypi
nilearn                   0.7.1                    pypi_0    pypi
numpy                     1.20.1                   pypi_0    pypi
numpydoc                  1.1.0                    pypi_0    pypi
olefile                   0.46                       py_0  
openssl                   1.1.1j               h27cfd23_0  
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.3            py38ha9443f7_0  
parso                     0.8.1              pyhd3eb1b0_0  
pcre                      8.44                 he6710b0_0  
pep517                    0.9.1                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.1.1            py38he98fc37_0  
pip                       21.0.1           py38h06a4308_0  
pluggy                    0.13.1                   pypi_0    pypi
prompt-toolkit            3.0.8                      py_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py                        1.10.0                   pypi_0    pypi
pybv                      0.5.0                    pypi_0    pypi
pycodestyle               2.6.0                    pypi_0    pypi
pydocstyle                5.1.1                    pypi_0    pypi
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.8.1              pyhd3eb1b0_0  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py38h05f1152_4  
pytest                    6.2.2                    pypi_0    pypi
pytest-cov                2.11.1                   pypi_0    pypi
pytest-sugar              0.9.4                    pypi_0    pypi
python                    3.8.8                hdb3f193_4  
python-dateutil           2.8.1              pyhd3eb1b0_0  
pytz                      2021.1             pyhd3eb1b0_0  
pyzmq                     20.0.0           py38h2531618_1  
qt                        5.9.7                h5867ecd_1  
readline                  8.1                  h27cfd23_0  
requests                  2.25.1                   pypi_0    pypi
scikit-learn              0.24.1                   pypi_0    pypi
scipy                     1.6.1            py38h91f5cce_0  
setuptools                52.0.0           py38h06a4308_0  
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0           py38h06a4308_0  
snowballstemmer           2.1.0                    pypi_0    pypi
sphinx                    3.5.2                    pypi_0    pypi
sphinx-bootstrap-theme    0.7.1                    pypi_0    pypi
sphinx-copybutton         0.3.1                    pypi_0    pypi
sphinx-gallery            0.8.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
toml                      0.10.2                   pypi_0    pypi
tornado                   6.1              py38h27cfd23_0  
traitlets                 5.0.5              pyhd3eb1b0_0  
urllib3                   1.26.3                   pypi_0    pypi
wcwidth                   0.2.5                      py_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.3                he6710b0_3  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
```
</details>

**Comment by alexrockhill** [comment]
> > Ok I installed a new environment and checked that I have all the same versions but I'm not able to reproduce the failed tests... anyone have a minute to help?
> 
> just ran `make` on an up to date local `main` branch, and everything passed
> 
> click details for output of `conda list`:

So then why are the tests failing? I'm at the same point, not sure what's different and wrong

**Comment by alexrockhill** [comment]
Ah so I think I've figured out that it is specific to the `Agg` backend, click works on rendered backends. Is there a better backend to use for tests?

**Comment by alexrockhill** [comment]
It might be a good idea to merge this so that the tests work and we can go back to working on the actual mne and bids related things and then change the requirements again when the new matplotlib version is sorted out

**Review by agramfort — COMMENTED** [review]
Ok to merge but remove edits to what’s new. Thanks 🙏

**Comment by hoechenberger** [comment]
Thank you, @alexrockhill !!

**Pull request merged**
