### PR TITLE
support missing dig

### LINKED ISSUE #450: `write_raw_bids` throws an error with mne >= 0.20
#### Describe the bug
Running `write_raw_bids` on a test recording results in an error with mne 0.21.dev0 and mne 0.20.*. Same code works fine with mne 0.19.2

#### Steps to reproduce
```python
from tempfile import mkdtemp
from pathlib import Path

import mne
import mne_bids

test_elekta = Path(mne.datasets.testing.data_path(verbose=True)) / 'misc' / 'test_elekta_3ch_raw.fif'
raw = mne.io.read_raw_fif(test_elekta, verbose=False)
bids_root = mkdtemp()
mne_bids.write_raw_bids(raw, 'sub-01_ses-01_run-05', bids_root=bids_root, verbose=False)
```

#### Expected results
A file is written to a bids dataset.

#### Actual results
The code raises the following error:

```
Traceback (most recent call last):
  File "<input>", line 10, in <module>
  File "c:\users\evgen\onedrive\projects\mne-bids\mne-bids\mne_bids\write.py", line 1092, in write_raw_bids
    overwrite, verbose)
  File "c:\users\evgen\onedrive\projects\mne-bids\mne-bids\mne_bids\dig.py", line 216, in _coordsystem_json
    coords = _extract_landmarks(dig)
  File "c:\users\evgen\onedrive\projects\mne-bids\mne-bids\mne_bids\utils.py", line 577, in _extract_landmarks
    landmarks = {d['ident']: d for d in dig
TypeError: 'NoneType' object is not iterable
```

#### Additional information
`mne.sys_info()`:

```sh
Platform:      Windows-10-10.0.18362-SP0
Python:        3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
Executable:    D:\software_windows\miniconda3\envs\mne-bids\python.exe
CPU:           Intel64 Family 6 Model 69 Stepping 1, GenuineIntel: 4 cores
Memory:        Unavailable (requires "psutil" package)
mne:           0.21.dev0
numpy:         1.18.5 {blas=C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info, lapack=C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info}
scipy:         1.4.1
matplotlib:    Not found
sklearn:       0.23.1
numba:         Not found
nibabel:       3.1.0
cupy:          Not found
pandas:        Not found
dipy:          Not found
mayavi:        Not found
pyvista:       Not found
vtk:           Not found
```

`mne_bids.__version__`:
```'0.5.dev0'```

### PR DESCRIPTION
**Pull request by agramfort**
closes #450

### CODE REVIEW

**Comment by jasmainak** [comment]
@agramfort you need to update `whats_new.rst` :)

**Comment by agramfort** [comment]
@larsoner any thought of how to fix the CI?

**Comment by larsoner** [comment]
these are regex so you probably need to escape the `(`, and you need a rebase / merge

**Comment by sappelhoff** [comment]
wouldn't it be better to fix the code upstream to adopt new behavior? instead of suppressing a deprecation warning?

**Comment by larsoner** [comment]
It has been:

https://github.com/scipy/scipy/blob/master/scipy/io/matlab/mio5.py#L853

But not released yet (though SciPy 1.5 is in the process of being released)

**Comment by agramfort** [comment]
Thx @larsoner

**Pull request merged**
