### PR TITLE
MRG: Replace tmpdir with tmp_path fixture

### PR DESCRIPTION
**Pull request by cbrnr**
This PR replaces the deprecated pytest `tmpdir` fixture with `tmp_path`. Because the tests do not run on my local system (mainly because the MNE package doesn't contain any test data), this is a first try (blindly replacing all occurrences).

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by cbrnr** [comment]
At some point (i.e. in another PR) we should also replace `os.path` with `pathlib`...

**Comment by cbrnr** [comment]
@sappelhoff @hoechenberger is it possible to still use a one-liner in this pattern? Unfortunately, `Path.mkdir()` returns `None` it seems...

Old:
```
bids_root = tmp_path.mkdir("bids")
```

New:
```
bids_root = tmp_path / "bids"
bids_root.mkdir()
```

**Comment by cbrnr** [comment]
```python
(bids_root := tmp_path / "bids").mkdir()
```

👀  - any objections? Of course this requires Python 3.8+...

**Comment by sappelhoff** [comment]
haha wow, that looks like making the most out of new features :laughing: Personally, I'd prefer two lines and keeping 3.7 compatibility. But I appreciate that new language feature, and if others like it better than the two-liner, I am happy to be overruled.

**Comment by cbrnr** [comment]
We can always change to `:=` once we drop support for 3.7 (MNE 0.25?).

**Comment by agramfort** [comment]
yes it's cool but let me play the grumpy one here (one more time)

I often say in my talks on software that should "write dumb code". Why?
Not everyone is a Python guru in our field and I want to maximize our
chances to welcome new contributors. All advanced code patterns
that are not absolutely necessary makes our projects less attractive
to new comers.

**Comment by cbrnr** [comment]
That's a valid point, and in general I agree. I just saw a meme on Twitter that went something like this:

- Beginner: `if`/`elif`/`else`
- Junior: `switch`
- Experienced: state machine
- Senior: `if`/`elif`/`else`

However, I think this needs to be decided case by case, otherwise we'll be stuck forever writing Python 1.0 code. For example, f-strings were a really nice addition that made things easier for users in most cases. The assignment operator is definitely more restricted to specific use cases (but this use case was actually one of the very few ones for me where I think it made the code simpler).

In any case, I'm fine with the 2-line variant here (especially since we still support 3.7).

**Comment by cbrnr** [comment]
> Yes, my personally feeling re the assignment expressions is that they REALLY make sense in for and while loops, but not sooo much in this particular case here :)

I really like that one here as well. Once again I wish Python was more like Julia, where an assignment is always an expression...

**Comment by agramfort** [comment]
I can live with 3 lines :)

**Comment by sappelhoff** [comment]
> I can live with 3 lines :)

me too :-)

+1 for walrus operator when we drop Python 3.7 support in the future (when it's end of life, I guess)

**Comment by agramfort** [comment]
I'll stick to 3 lines and if/then/else as a Beginner or Senior developer :)

>

**Comment by hoechenberger** [comment]
I'm all for the walrus but with the specific case here I think it makes things slightly more difficult to read. I agree with Clemens that it's a pity that Path.mkdir() doesn't return self. ☠️

**Comment by hoechenberger** [comment]
> > I can live with 3 lines :)
> 
> 
> 
> me too :-)
> 
> 
> 
> +1 for walrus operator when we drop Python 3.7 support in the future (when it's end of life, I guess)

Is actuallynopt for dropping it next year, so that we always support the latest 3 versions. To keep CI resource demands manageable if nothing else ...

**Comment by sappelhoff** [comment]
> Because the tests do not run on my local system (mainly because the MNE package doesn't contain any test data)

Couldn't you just clone MNE-Python and in your mne-bids environment do a local `pip -e .` install of the MNE-Python clone?

**Comment by cbrnr** [comment]
> Couldn't you just clone MNE-Python and in your mne-bids environment do a local pip -e . install of the MNE-Python clone?

I don't know, shouldn't the tests also work with a pip installed mne? It really looks like the pip package doesn't contain the test datasets.

**Comment by sappelhoff** [comment]
> I don't know, shouldn't the tests also work with a pip installed mne? It really looks like the pip package doesn't contain the test datasets.

Yes, MNE via pip install does not include the test data as far as I can tell: https://github.com/mne-tools/mne-python/blob/5bafe5287dd27ef6e07a64609615326110536578/MANIFEST.in#L75-L84

That's been this way since mne-bids was started, so we always relied on a local clone + local install:

https://github.com/mne-tools/mne-bids/blob/main/CONTRIBUTING.md#clone-mne-python-and-install-it-from-the-git-repository


Whether that's a good thing or not is another question :)

**Comment by cbrnr** [comment]
Thanks for clarifying @sappelhoff. I think it is confusing that a git clone behaves differently than the pip package. I did ask myself why a git clone of the current main branch was necessary, but thought that I could just use the pip package instead.

**Comment by hoechenberger** [comment]
> I did ask myself why a git clone of the current main branch was necessary, but thought that I could just use the pip package instead.

Oh wow, mind = blown 🤯 

I never realized this before either

**Comment by cbrnr** [comment]
So I guess this pretty much answers @sappelhoff's previous question whether this was a good thing... 😄 

Maybe all tests can be changed to use data from the `mne-testing-data` repo (that can be downloaded with `mne.datasets.testing.data_path()`?

**Comment by hoechenberger** [comment]
I don't think it's necessary, since the development version of MNE-BIDS typically requires the development version of MNE-Python, which cannot be installed from PyPI…

**Comment by sappelhoff** [comment]
> Maybe all tests can be changed to use data from the mne-testing-data repo (that can be downloaded with mne.datasets.testing.data_path()?

or MNE-Python starts to ship the test data :)

IMHO we don't need to fix it - it's more effort than it's worth

**Comment by cbrnr** [comment]
True. If at all MNE should include the test data.

**Comment by agramfort** [comment]
We cannot ship them. It’s too big for pypi. I tried ;)

**Comment by hoechenberger** [comment]
@cbrnr What's the status here? Need a hand to get this finished?

**Comment by cbrnr** [comment]
That would be great!

**Comment by hoechenberger** [comment]
@cbrnr Could you give me a quick reminder what remains to be done?

**Comment by cbrnr** [comment]
Basically get all tests to pass. I've searched and replaced, but now e.g. `tmpdir.mkdir()` needs to be replaced with the two/three lines that we discussed in another issue (where I wanted to use the assignment operator).

**Comment by hoechenberger** [comment]
@cbrnr Turns out we didn't need those `mkdir()`s in most cases. So this debate was a little misguided 😅 But it was fun to discuss anyway haha

**Comment by cbrnr** [comment]
@hoechenberger this was a discussion in the `mne-python` repo – how is `mkdir()` not necessary?

**Comment by hoechenberger** [comment]
@cbrnr In many of the tests we created BIDS root dirs manually, but `write_raw_bids()` creates them automatically for us, so I could drop loads of `mkdir()` calls

**Comment by cbrnr** [comment]
OK, so it's specific to the code in this repository and not a general optimization you could also apply to the code in `mne-python`.

**Comment by hoechenberger** [comment]
@cbrnr Yep, sorry for the confusion! :)

**Comment by hoechenberger** [comment]
I'm not sure why the doc build is failing..?

**Comment by cbrnr** [comment]
Seems unrelated, maybe restart?

**Comment by hoechenberger** [comment]
@cbrnr I've restarted Circle, let's see …

**Comment by hoechenberger** [comment]
Now it's a different error … I'm a bit clueless. Seems like a problem with `sphinx-gallery`?

@larsoner Any idea what's up with our documentation build here?

https://circleci.com/gh/mne-tools/mne-bids/5501

**Comment by hoechenberger** [comment]
Seems there was a new Sphinx release a few hours ago (4.3.0); let's see if pinning to an older version helps.

**Comment by larsoner** [comment]
Always check MNE-Python first :)

https://github.com/mne-tools/mne-python/pull/9992

**Comment by hoechenberger** [comment]
You telling me that you pushed a fix to MNE-Python 2 hours ago, while the problematic new Sphinx release was made just one hour before that?? 

**DAMN** 🤩🥸🥳😎❤️

**Comment by cbrnr** [comment]
I wouldn't be surprised if @larsoner also made the Sphinx release himself 😂.

**Comment by larsoner** [comment]
Technically I pushed the fix to SciPy first, then MNE-Python

**Comment by larsoner** [comment]
(And really this is partially my fault because I had seen the error on Sphinx 5.0.dev0 some weeks ago but didn't take the time to open an upstream issue with pydata-sphinx-theme :( )

**Comment by hoechenberger** [comment]
Alright, we're green.

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @cbrnr !

**Comment by cbrnr** [comment]
Thanks @hoechenberger!

**Comment by sappelhoff** [comment]
Thanks all! :rocket:

**Pull request merged**
