### PR TITLE
[MRG] add CSS to truncate long version string

### LINKED ISSUE #1205: After switch to hatchling&hatch-vcs: heading in documentation is taking up too much space
see: https://mne.tools/mne-bids/dev/index.html

**now:**

image

---

**before:**

image

### PR DESCRIPTION
**Pull request by drammock**
PR Description
--------------

closes #1205 by truncating long version strings (with `text-overflow: ellipsis`)

Merge checklist
---------------

Maintainer, please confirm the following before merging.
If applicable:

- [ ] All comments are resolved
- [ ] This is not your own PR
- [x] All CIs are happy
- [x] PR title starts with [MRG]
- [x] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [x] New contributors have been added to [CITATION.cff](https://github.com/mne-tools/mne-bids/blob/main/CITATION.cff)
- [x] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by drammock** [comment]
Doc build is failing with

> FileNotFoundError: File does not exist: "/home/circleci/mne_bids_env/lib/python3.9/site-packages/mne/data/fsaverage/fsaverage-fiducials.fif"

https://app.circleci.com/pipelines/github/mne-tools/mne-bids/5724/workflows/eec55885-c064-4fb8-83a2-825269e3fb48/jobs/7919

I'll push the changelog entry but @sappelhoff can you take over here?

**Comment by hoechenberger** [comment]
I can fix the issue 

@cbrnr @larsoner @sappelhoff

**Comment by larsoner** [comment]
Sure, I opened https://github.com/mne-tools/mne-python/pull/12280 which will hopefully at least set up CIs to show the problem

**Review by sappelhoff — COMMENTED** [review]
thanks Dan! Waiting for the other bug to be fixed to check out how this looks.

**Comment by drammock** [comment]
here's the rendered doc: https://output.circle-artifacts.com/output/job/a36b9461-2f17-4d84-ba0a-70d85c36c8cd/artifacts/0/dev/index.html

Looks as expected:
Screenshot 2023-12-08 at 16-16-40 MNE-BIDS — MNE-BIDS 0 15 0 dev17 g47168603 documentation

codecov failure seems spurious.

**Pull request merged**
