### PR TITLE
[MRG] DOC: add sphinx-copybutton extension

### PR DESCRIPTION
**Pull request by sappelhoff**
This is a quality of life PR, for readers of the docs to more easily copy code blocks.

There will be a small "copy"  icon for each codeblock ... when clicking on it, users copy the code - automatically removing `>>>` and `$ `

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [x] All comments resolved
- [x] This is not your own PR
- [x] All CIs are happy
- [x] PR title starts with [MRG]
- ~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated~
- ~PR description includes phrase "closes <#issue-number>"~

### CODE REVIEW

**Comment by sappelhoff** [comment]
I think this is awesome.

Just look at the installation page and try to copy some cells: https://3558-89170358-gh.circle-artifacts.com/0/dev/install.html

... or copying the [quickstart codeblock](https://3558-89170358-gh.circle-artifacts.com/0/dev/use.html#id13)

... or look at an [example, and copy some cells](https://3558-89170358-gh.circle-artifacts.com/0/dev/auto_examples/convert_group_studies.html#sphx-glr-auto-examples-convert-group-studies-py)

**Comment by jasmainak** [comment]
works for me :)

**Comment by hoechenberger** [comment]
Yep, all nice and everything, but have you checked out the [Study Template docs](https://mne.tools/mne-study-template/) recently? 😍
I'm never going to use Sphinx again, seriously… except for the gallery, maybe.

**Comment by sappelhoff** [comment]
looks nice! And cool to see that there are docs now! :)

I like Mkdocs, but with the experiences I am having over at bids-standard/bids-specification, I would choose sphinx everytime. :laughing: 

but granted: lots of my complaints about mkdocs are about the lack of easy pdf conversion ... like available with sphinx. And that's arguably only important for things like the BIDS spec.

**Comment by sappelhoff** [comment]
also, can you do automatic API docs and "view source code" links with mkdocs?

**Comment by hoechenberger** [comment]
> also, can you do automatic API docs and "view source code" links with mkdocs?

Yes that does work :) For functions and classes, at least.
Why would you think PDF is important? I would never want to read BIDS as a PDF… am I overlooking some advantages here?

**Comment by hoechenberger** [comment]
(btw I think this is good to merge, just didn't do it bc there's no [MRG] in the PR title so far!)

**Comment by sappelhoff** [comment]
> I would never want to read BIDS as a PDF… am I overlooking some advantages here?

old people, ... and sometimes companies etc. like to have a versioned PDF that they can print, put in a file drawer, and have it unchanged by anyone. :angel:

**Comment by hoechenberger** [comment]
Thanks @sappelhoff!

**Comment by hoechenberger** [comment]
> old people, ... and sometimes companies etc. like to have a versioned PDF that they can print, put in a file drawer, and have it unchanged by anyone. 👼

Hehe :)

**Pull request merged**
