### PR TITLE
[MRG] use environment.yml in appveyor

### PR DESCRIPTION
**Pull request by sappelhoff**
follow up for https://github.com/mne-tools/mne-bids/pull/281#issuecomment-549649843

Let's see if this works.

It'd be an improvement, because there are less files where we need to monitor version numbers. --> use `environment.yml` in Circle, Travis, and Appveyor

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [x] All comments resolved
- [ ] This is not your own PR
- [x] All CIs are happy
- [x] PR title starts with [MRG]
- ~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated~
- ~PR description includes phrase "closes <#issue-number>"~
- [x] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by sappelhoff** [comment]
> however it seems we have no build that test the minimal set of dependencies.

true

> ok to add a travis build that just uses numpy, scipy and mne?

that would kind of defeat the purpose of this PR (having to update less files), so we could also just modify this PR and make Appveyor our build that uses minimal dependencies?

wdyt @jasmainak ?

**Comment by agramfort** [comment]
I would like to make sure that minimal deps version is working. We had
to do this
in the past for mne as we had suddenly put a hard dep on matplotlib
without noticing

**Comment by jasmainak** [comment]
I agree with @agramfort that we should check minimum deps. I am not a big fan of the common environment file approach. You may silently introduce dependencies.

**Comment by sappelhoff** [comment]
Fair enough, but that's a different issue.

MNE-BIDS *does* run with just mne, numpy, scipy

However, our **test suite** needs the optional packages

If you look at the appveyor code so far, you'll also see that this was *not* a minimal install either (it also installs nibabel, and pybv).

So I think we can open a new issue for having a test suite with a minimal installation. I still find this current PR mergeable given that it makes nothing worse, only some stuff more clear.

**Comment by jasmainak** [comment]
@agramfort ok for you?

**Comment by agramfort** [comment]
ok for me. See https://github.com/mne-tools/mne-bids/pull/319

**Pull request merged**
