### PR TITLE
always use bids naming for split files

### PR DESCRIPTION
**Pull request by agramfort**
cc @hoechenberger @sappelhoff @jasmainak

### CODE REVIEW

**Comment by jasmainak** [comment]
Travis is failing ...

**Comment by hoechenberger** [comment]
Seems like the right thing to do, as we discussed privately yesterday

**Comment by agramfort** [comment]
hum it's not so easy as now it write with _split-01 any file even if it's less than 2GB...

mne-python needs to be fixed...

**Comment by hoechenberger** [comment]
Yes this clearly is a bug in MNE!

**Comment by hoechenberger** [comment]
This has been fixed upstream. I just restarted CI. This is good to merge once CI goes green.

**Review by sappelhoff — APPROVED** [review]
great, thanks a lot also for the upstream fix alex (and eric)

**Comment by hoechenberger** [comment]
Thanks @agramfort!

**Pull request merged**
