### PR TITLE
[WIP] TESTS: Make tests fail on warnings

### PR DESCRIPTION
**Pull request by hoechenberger**
PR Description
--------------
Make tests fail on warnings, as discussed in GH-372.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"
- [ ] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by agramfort** [comment]
I would prefer that you catch them one by one as here you mask all of them apparently

**Comment by hoechenberger** [comment]
@agramfort My idea is to first explicitly mask all warnings that currently show up; and then we can get started removing the filters one after the other, e.g. the `FutureWarning` filter I would remove while working on #372

**Comment by agramfort** [comment]
whatever you think is best if we agree on objective

>

**Comment by hoechenberger** [comment]
> whatever you think is best if we agree on objective

Yes, objective is clear :)

**Comment by hoechenberger** [comment]
All CIs are green, although Travis somehow still shows up orange here (but all of its tests passed). May I merge this? @agramfort @jasmainak

**Comment by agramfort** [comment]
ok let's now fix each type of warnign is a dedicated PR

**Pull request merged**
