### PR TITLE
fixed string subID bug

### LINKED ISSUE #1290: Failed to create new participants.tsv entry when subject ID is non numeric
### Description of the problem

Trying to write a new BIDS file, but crashes seemingly due to trying to convert a string to a float

### Steps to reproduce

1. Load a BIDS dataset with a subject ID containing a letter or anything that can't be converted to a float
2. try to save that subject to a new BIDS directory using 'write_raw_bids'

### Expected results

write the subject and add entry to participants.tsv

### Actual results

Traceback (most recent call last):
  File "C:\Users\ae166\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\pydevd.py", line 1557, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ae166\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\ae166\git\SentenceRep_analysis\analysis\fix\clean.py", line 39, in <module>
    save_derivative(fixed, layout, "clean", True)
  File "<decorator-gen-455>", line 12, in save_derivative
  File "C:\Users\ae166\git\IEEG_Pipelines\ieeg\io.py", line 250, in save_derivative
    write_raw_bids(run, bids_path, allow_preload=True, format=format,
  File "<decorator-gen-445>", line 12, in write_raw_bids
  File "C:\Users\ae166\git\mne-bids\mne_bids\write.py", line 1923, in write_raw_bids
    _participants_tsv(
  File "C:\Users\ae166\git\mne-bids\mne_bids\write.py", line 494, in _participants_tsv
    exact_included = _contains_row(
                     ^^^^^^^^^^^^^^
  File "C:\Users\ae166\git\mne-bids\mne_bids\tsv_handler.py", line 86, in _contains_row
    row_value = np.array(row_value, dtype=data_value.dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'sub-D0024'

### Additional information

Platform             Windows-10-10.0.19045-SP0
Python               3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:24:51) [MSC v.1940 64 bit (AMD64)]
Executable           C:\Users\ae166\.conda\envs\preprocess\python.exe
CPU                  Intel64 Family 6 Model 158 Stepping 9, GenuineIntel (8 cores)
Memory               63.9 GB
Core
├☑ mne               1.7.1 (latest release)
├☑ numpy             1.26.4 (MKL 2024.1-Product with 4 threads)
├☑ scipy             1.14.0
└☑ matplotlib        3.9.1Backend qtagg is interactive backend. Turning interactive mode on.
 (backend=qtagg)
Numerical (optional)
├☑ sklearn           1.5.1
├☑ nibabel           5.2.1
├☑ dipy              1.9.0
├☑ pandas            2.2.2
├☑ h5io              0.2.4
├☑ h5py              3.11.0
└☐ unavailable       numba, nilearn, openmeeg, cupy
Visualization (optional)
├☑ pyvista           0.44.1 (OpenGL 4.5.0 - Build 30.0.101.1692 via Intel(R) HD Graphics 630)
├☑ pyvistaqt         0.11.1
├☑ vtk               9.3.1
├☑ qtpy              2.4.1 (PySide6=6.7.2)
├☑ pyqtgraph         0.13.7
├☑ mne-qt-browser    0.6.3
└☐ unavailable       ipympl, ipywidgets, trame_client, trame_server, trame_vtk, trame_vuetify
Ecosystem (optional)
├☑ mne-bids          0.15.0
├☑ eeglabio          0.0.2-4
├☑ edfio             0.4.3
├☑ pybv              0.7.5
└☐ unavailable       mne-nirs, mne-features, mne-connectivity, mne-icalabel, mne-bids-pipeline, neo, mffpy

### PR DESCRIPTION
**Pull request by Aaronearlerichardson**
PR Description
--------------

- fixes #1290 

Merge checklist
---------------

Maintainer, please confirm the following before merging.
If applicable:

- [ ] All comments are resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] New contributors have been added to [CITATION.cff](https://github.com/mne-tools/mne-bids/blob/main/CITATION.cff)
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by Aaronearlerichardson** [comment]
will fix #1290

**Comment by sappelhoff** [comment]
Thanks @Aaronearlerichardson! Could you please modify one of our tests to cover this case?

Also, please feel free to add yourself to the list of authors, and add a changelog entry: https://github.com/mne-tools/mne-bids/blob/main/CONTRIBUTING.md#instructions-for-first-time-contributors

**Comment by sappelhoff** [comment]
@Aaronearlerichardson please let me know if you intend to work on the final points I mentioned in my comment above, and what your expected timeline would be. If not, somebody else could perhaps take over (as long as you supply a few of your details to list you in the authors lists)

**Comment by Aaronearlerichardson** [comment]
@sappelhoff hope this covers it

**Comment by sappelhoff** [comment]
Thanks a lot @Aaronearlerichardson :-) 

> @sappelhoff hope this covers it

I added a few more commits, but thanks for the start and the contribution in general

**Pull request merged**
