### PR TITLE
[MRG] allow EEGLAB to also handle .set+.fdt combinations

### LINKED ISSUE #88: EEGLAB: allow to copy .fdt files and update the pointer in corresponding .set
EEGLAB files are MATLAB files ... albeit with a `.set` extension instead of the usual `.mat`. The EEGLAB files can contain the EEG data in a matlab struct field called `data`. However, this `data` field can alternatively contain a link to an accompanying (separate) `.fdt` (=FloatDaTa) file. 

Currently MNE-BIDS only allows the standalone `.set` files and thorws an error when an `.set`+`.fdt` combination is used. This should be fixed, see:

https://github.com/mne-tools/mne-bids/blob/7403fc56b33bfe9b61e2cd7ee214ab9ad24312b0/mne_bids/utils.py#L497-L505

### PR DESCRIPTION
**Pull request by sappelhoff**
fixes #88

### CODE REVIEW

**Comment by sappelhoff** [comment]
okay, this might have been easier than expected. Locally, all my tests pass - let's see what the CI says, otherwise this is ready to be merged.

**Comment by jasmainak** [comment]
Looks great, merged. Thanks @sappelhoff !

**Comment by jasmainak** [comment]
And that was pull request #100 :tada:

**Comment by sappelhoff** [comment]
celebraaation :-)

**Pull request merged**
