### PR TITLE
add TOC in sidebar to doc pages

### PR DESCRIPTION
**Pull request by agramfort**
cc @hoechenberger

### CODE REVIEW

**Comment by hoechenberger** [comment]
Very neat!

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
CI failure related to https://stackoverflow.com/a/21060677 ?

Maybe related to some tests I recently added?

**Comment by agramfort** [comment]
did we change anything on brainvision side?

**Comment by hoechenberger** [comment]
@agramfort 
> did we change anything on brainvision side?

No, but I touched EEGLAB stuff, maybe there's a side effect? Can you try disabling the EEGLAB tests and see if it passes then?

**Comment by agramfort** [comment]
this one should be good to go @hoechenberger

**Review by hoechenberger — APPROVED** [review]
@agramfort Merge if happy

**Review by sappelhoff — APPROVED** [review]
looks pretty, thanks!

**Pull request merged**
