### PR TITLE
[MRG] FIX: add support for 2nd order gradient compensation

### PR DESCRIPTION
**Pull request by jasmainak**
PR Description
--------------

Hey guys, a colleague from Karim Jerbi's lab reached out to me who was having trouble with converting to BIDS with 2nd order gradient compensation. I followed the fix of @agramfort in #549 

If you want to reproduce the data and script was shared here:

https://drive.google.com/file/d/1mfEsDg6wVH6MjUPSCrFSOTRhtHdbFB0L/view?usp=sharing

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by hyruuk** [comment]
Hi ! Thanks for the quick reaction @jasmainak :)
After trying this fix on a dataset that contains both 3rd order and 2nd order GC it seems that this fix only reverts the problem : now the `KeyError: 'mag'` appears when processing the 3rd order compensated data and not with the 2nd order. I am not sure how to cleanly fix both situations.

**Review by agramfort — APPROVED** [review]
+1 for MRG after a what's new update

thx @jasmainak

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Thanks @jasmainak!

**Comment by jasmainak** [comment]
Thanks @hoechenberger for doing the changelog :)

**Pull request merged**
