### PR TITLE
[WIP] MAINT Add documentation on conda packaging

### LINKED ISSUE #267: Update How to make a release guide to include conda-forge package
https://github.com/mne-tools/mne-bids/pull/266#issuecomment-528043905

### PR DESCRIPTION
**Pull request by hoechenberger**
PR Description
--------------
Add documentation section to `CONTRIBUTING.md` on how to update / maintain the `conda-forge` package.

This document is incorporated into the `sphinx`-generated documentation via `m2r` to avoid redundancy. The `Github` navbar link was replaced with a `Contribute` link, leading to this contribution guide.

Closes #267.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"
- [ ] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by sappelhoff** [comment]
Cool, thanks a lot @hoechenberger! Do we want to make the CONTRIBUTING guide accessible from the website though?

I had a wiki entry in mind for simplicity, but I am open to this. ping for opinion @jasmainak

**Comment by hoechenberger** [comment]
I don’t have a strong opinion on this one, so I’m open for changes. My approach was partly inspired by the pandas website:

https://dev.pandas.io/contribute.html

**Comment by jasmainak** [comment]
I agree with @sappelhoff that we should edit the wiki directly. It's easier to tweak during the release. It's only maintainers who need to work with this stuff.

@hoechenberger I am fine adding you as a maintainer so you can edit it directly. Okay for you @sappelhoff @agramfort ?

**Comment by agramfort** [comment]
a wiki package for release mechanism is easier as it targets very few
people (aka maintainers)

+1 to add @hoechenberger <https://github.com/hoechenberger> as maintainer.

**Comment by hoechenberger** [comment]
Ok let’s do this :) shall I close this PR, then?

**Comment by sappelhoff** [comment]
+1 from my side

+1 to close

**Comment by hoechenberger** [comment]
I've [added](https://github.com/mne-tools/mne-bids/wiki/How-to-make-a-release#updating-the-conda-package) the `conda` guide to the wiki, and created a table of contents too.

**Comment by jasmainak** [comment]
Excellent, thanks @hoechenberger !

**Pull request closed without merging**
