### PR TITLE
[MAINT] Require MNE-Python `main` until `0.23.1` release

### PR DESCRIPTION
**Pull request by alexrockhill**
I have no idea what's causing the CIs to fail here https://github.com/mne-tools/mne-bids/pull/859 and I assume it's not something to do with the PR but I have failed to replicate the issue locally so I'm just pushing an empty commit just to make sure.

### CODE REVIEW

**Comment by alexrockhill** [comment]
Oh that it's just a dependency on a 0.24 function, not sure why it took me so long to figure that out

**Comment by alexrockhill** [comment]
Is that the best way to solve this for now, or should there be a check for version 0.24 and if not an error that the function can't be used?

**Review by agramfort — APPROVED** [review]

**Comment by hoechenberger** [comment]
-1 on merging this, this is essentially disabling the test, not fixing it :) I can have a look at the issue you're experiencing sometime later today!

**Review by hoechenberger — DISMISSED** [review]
-1 on merging this, this is essentially disabling the test, not fixing it :) I can have a look at the issue you're experiencing sometime later today!

**Comment by alexrockhill** [comment]
> -1 on merging this, this is essentially disabling the test, not fixing it :) I can have a look at the issue you're experiencing sometime later today!

The issue is that someone else added a dependency on a function in `main` (development branch). I'm not sure how that passed the CIs but it failed for my PR. This doesn't disable the tests, it just runs all the tests with the development version until the next release. I think the only other solution is to remove the changes that depend on `get_chpi_info` until the next `mne-python` release but that won't be for a while.

**Comment by alexrockhill** [comment]
I guess I should change the `requirements.txt` to the bleeding edge `mne-python` though if this were to merge. We've done that in `mne-python`, i.e. requiring the bleeding edge `mne-bids` until the next version release.

**Comment by alexrockhill** [comment]
Ok @hoechenberger, does that make more sense? Now we've just bumped the requirements up to the development `mne-python` until the next release.

**Comment by hoechenberger** [comment]
> The issue is that someone else added a dependency on a function in `main` (development branch). I'm not sure how that passed the CIs but it failed for my PR

Oh, wow. I didn't have time to look yet, unfortunately. Only tomorrow morning …
Since the next MNE-Python release can be expected soon, maybe it's okay to just move ahead …
@sappelhoff WDYT?

**Comment by sappelhoff** [comment]
So someone (who?, which PR?)  added a new function (or changed an existing one? which one?) to MNE-BIDS that REQUIRES something from MNE-Python main? If yes, why did the CIs pass in that PR? --> We only merge PRs with passing CIs :thinking: 

Please elaborate @alexrockhill and help us with nice crosslinks to code and PRs! :)

**Comment by alexrockhill** [comment]
I'm not the one who merged the PR, so I have no idea who did it, I was just the next person to run the CIs. I can look and see though.

**Comment by alexrockhill** [comment]
So looks like it was this one https://github.com/mne-tools/mne-bids/pull/794 four months ago. As far as I can tell, version 0.23 doesn't have `get_chpi_info` https://github.com/mne-tools/mne-python/blob/maint/0.23/mne/chpi.py but the logs are expired so I can't tell how the CIs passed and what versions they were running....

**Comment by sappelhoff** [comment]
Okay, thanks. That's just weird that now the CIs start failing all of a sudden ... and not even on main (yet?), even though we run it every night, see: https://github.com/mne-tools/mne-bids/blob/e460331877dc633fe028364d5e310320eced5d4c/.github/workflows/unit_tests.yml#L11-L12

I'll leave this to you and @hoechenberger, I am fine with depending on MNE-Python `main` for now ... especially because 0.23.1 will be out soon :-)

**Comment by alexrockhill** [comment]
> Okay, thanks. That's just weird that now the CIs start failing all of a sudden ... and not even on main (yet?), even though we run it every night, see:
> 
> https://github.com/mne-tools/mne-bids/blob/e460331877dc633fe028364d5e310320eced5d4c/.github/workflows/unit_tests.yml#L11-L12
> 
> I'll leave this to you and @hoechenberger, I am fine with depending on MNE-Python `main` for now ... especially because 0.23.1 will be out soon :-)

No idea what happened or how that happened. I guess 0.23 could have been changed but I don't think it's worth looking into, I think maybe just say very odd and I wish we knew how that happened but the most important thing is that it works.

**Comment by sappelhoff** [comment]
yes, maybe it's due to some commits to https://github.com/mne-tools/mne-python/commits/maint/0.23 ... which is what we use in our CI (we are not using the pypi release). +1 to go ahead and just fix it.

**Comment by hoechenberger** [comment]
+1 on moving forward here

**Comment by agramfort** [comment]
>
> +1 on moving forward here
>
+1

**Comment by sappelhoff** [comment]
Thanks @alexrockhill 

All of us: Let's not forget to pin this `main` back to `0.23.1` once it is released :-)

**Comment by hoechenberger** [comment]
It's time! ;)

**Pull request merged**
