### PR TITLE
make acq time optional

### LINKED ISSUE #813: acq_time is optional in scans.tsv files while we make it required
see:

```
~/work/src/mne-bids/mne_bids/read.py in _handle_scans_reading(scans_fname, raw, bids_path, verbose)
    206     data_fname = bids_path.datatype + '/' + fname
    207     fnames = scans_tsv['filename']
--> 208     acq_times = scans_tsv['acq_time']
    209     row_ind = fnames.index(data_fname)
    210

KeyError: 'acq_time'
```

### PR DESCRIPTION
**Pull request by agramfort**
closes #813

### CODE REVIEW

**Review by sappelhoff — APPROVED** [review]
Thanks @agramfort

**Comment by agramfort** [comment]
@hoechenberger feel free to merge

thx @sappelhoff for the quick review

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Good to merge once the doc build goes green.

**Comment by hoechenberger** [comment]
Thanks @agramfort!

**Pull request merged**
