### PR TITLE
MRG: ENH: Support full range of  hand & sex options

### PR DESCRIPTION
**Pull request by hoechenberger**
PR Description
--------------
The standard demands a much more extensive list of valid values than we are currently supporting in `master`:
https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#participants-file

I realized this when reading a dataset with IMHO properly specified sex & handedness, yet ended up without these values
in `raw.info['subject_info']`.

<strike>WIP: need to add tests and potentially changelog entry.</strike>

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by hoechenberger** [comment]
This is ready to go from my end.

**Review by sappelhoff — COMMENTED** [review]
remember that these are only RECOMMENDATIONS, because when BIDS 1.0 was released, nobody wanted to strictly define (REQUIRE / "MUST") the set of acceptable options for hand, sex, age

so now we cannot put REQUIRED anymore, because it would break backwards compatibility.

c.v. https://github.com/bids-standard/bids-specification/issues/458

**Review by sappelhoff — APPROVED** [review]

**Comment by hoechenberger** [comment]
@sappelhoff thanks for the clarification!

This doesn't affect the PR as such, though, or does it?

**Comment by sappelhoff** [comment]
> This doesn't affect this PR as such, though, or does it?

no, the PR is good and useful (thanks) -> it only serves as a reminder that user can still do some funny mapping like: `Female = FemPartici` ... and it's still valid BIDS (albeit not recommended)

**Comment by hoechenberger** [comment]
It's actually weird that there is no fixed internal mapping on the BIDS side, and of users wish to deviate, they will have to provide the appropriate schema... could be super easy to add since we're already using JSON files everywhere.

**Comment by hoechenberger** [comment]
@sappelhoff please merge if you're happy :)

**Comment by sappelhoff** [comment]
>  if users wish to deviate, they would have to provide the appropriate schema

if users *do* deviate, then it is RECOMMENDED (again :rofl: ) to provide the schema --> so if we find "n/a" with MNE-BIDS ... we *could* try to get a  `participants.json` file

and if we miraculously find one, we can check for the `sex` ... etc. columns.

**Comment by hoechenberger** [comment]
> if users _do_ deviate, then it is RECOMMENDED (again 🤣 ) to provide the schema --> so if we find "n/a" with MNE-BIDS ... we _could_ try to get a `participants.json` file
> 
> and if we miraculously find one, we can check for the `sex` ... etc. columns.

Well but is what would happen not the following:

- We find an unknown column, say, `sex_or_gender`, in `participants.tsv`
- We open `participants.json` to get info about this
    - We **do** find info about this column, something of the kind:
       ```
       This column codes for sex and gender, which always matched in our participants.
       Acceptable values are: "Fem" for "female" and "Mal" for "male"
   - Now… how would a computer know that this is to be mapped to `sex`?

**Comment by sappelhoff** [comment]
Like in this file: https://github.com/bids-standard/bids-examples/blob/master/eeg_matchingpennies/participants.json

The keys in the JSON map to the columns of the TSV file

and each key in the JSON contains an object with the following keys:

https://bids-specification.readthedocs.io/en/latest/02-common-principles.html#tabular-files

and that's defined, so at least there's that.

**Comment by hoechenberger** [comment]
Yeah but… taking the example from the section of the specs that you linked to:

```
Example of a hypothetical *_events.json file, accompanying an *_events.tsv file. 
Note that the JSON file contains a key describing an arbitrary column
stim_presentation_side in the TSV file it accompanies. See task events section for
more information.


{
  "stim_presentation_side": {
    "Levels": {
      "1": "stimulus presented on LEFT side",
      "2": "stimulus presented on RIGHT side"
    }
  }
}
```
This only helps me to automatically annotate the data, at best. But it wouldn't help me to e.g. map this information from BIDS to MNE's FIFF… Oh well.

**Comment by sappelhoff** [comment]
true ... :-/

**Comment by jasmainak** [comment]
> if users do deviate, then it is RECOMMENDED (again 🤣 ) to provide the schema

I didn't read everything carefully, but @sappelhoff this just reinforces my point that any nerding on `bids-specification` github should be banned unless accompanied by code, usecases and PRs to update the datasets :)

**Comment by sappelhoff** [comment]
> this just reinforces my point that any nerding on bids-specification github should be banned unless accompanied by code, usecases and PRs to update the datasets :)

yeah, you are right in principle :+1:

**Pull request merged**
