### PR TITLE
[BUG] Fix for mpl 3.4 requirements

### PR DESCRIPTION
**Pull request by alexrockhill**
Fix for previous problem https://github.com/mne-tools/mne-bids/pull/756

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Review by hoechenberger — COMMENTED** [review]
I'm not sure I understand what's happening here... the idea of this test was to simulate user interaction, which includes the key press event. Why is this not working in 3.4 anymore..?

**Comment by alexrockhill** [comment]
> I'm not sure I understand what's happening here... the idea of this test was to simulate user interaction, which includes the key press event. Why is this not working in 3.4 anymore..?

See the discussion in this issue about close events with a non-interactive backend not firing https://github.com/matplotlib/matplotlib/issues/18609. So you are simulating a click roughly, but for `Agg` you just have to skip to simulating the emitted event.

**Comment by alexrockhill** [comment]
Also, I'm really not sure why it worked in previous versions of mpl, I looked into it a bit and I couldn't tell you

**Comment by hoechenberger** [comment]
Should we maybe use an interactive backend then? And test in a virtual X server?

**Comment by alexrockhill** [comment]
> Should we maybe use an interactive backend then? And test in a virtual X server?

It sounds like that could slow down the tests but maybe that would be good, not sure

**Comment by agramfort** [comment]
Are we sure it’s not treated as a bug by mpl so it’s fixed in one Minor release ?

**Comment by hoechenberger** [comment]
> Are we sure it’s not treated as a bug by mpl so it’s fixed in one Minor release ?

In the linked issue they propose how to fix this, but it's been stale since…

**Comment by alexrockhill** [comment]
> Are we sure it’s not treated as a bug by mpl so it’s fixed in one Minor release ?

It looks like they labeled the issue for discussion and they're not sure if they do want a non-interactive figure to fire a close event because they don't think it makes sense for a non-interactive figure to close. So it might happen but I would guess not in the next version release. It's not a new issue though so, again, I'm really not sure why the tests started failing upon the 3.4.0 release and why adding this `_close` call fixed them, a bit of a mystery...

**Comment by agramfort** [comment]
Ok maybe let’s be pragmatic here and merge ... your call

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Yes let's merge once we're green

**Comment by hoechenberger** [comment]
@alexrockhill The tests are stalled :(

**Comment by hoechenberger** [comment]
I reverted your last commit, thinking this might fix CI, but I'm not sure if it's actually related…

**Comment by alexrockhill** [comment]
> I reverted your last commit, thinking this might fix CI, but I'm not sure if it's actually related…

It has been stalling for the last couple and for a PR on mne-python related to this issue... I think it's a Microsoft server issue

**Comment by hoechenberger** [comment]
Ok … shall I revert my reversal than? ;)

**Comment by alexrockhill** [comment]
Sure, it the last commit doesn't really change anything but it does have the simulated click

**Comment by alexrockhill** [comment]
So I looked a bit more and it looks like this loop in mne.viz._figure.py (line 557) is doing an infinite loop

```
# Clean up child figures (don't pop(), child figs remove themselves)
while len(self.mne.child_figs):
    fig = self.mne.child_figs[-1]
    close(fig)
```

It appears they don't remove themselves any longer maybe

**Comment by alexrockhill** [comment]
Maybe there is also something going on with the test servers, as they are really slow but the tests pass locally so I think this is an okay solution for testing, it would be great if mpl could sort this out so that the tests didn't have to do these weird workarounds

**Comment by hoechenberger** [comment]
yeah let's look at this again tomorrow

**Comment by alexrockhill** [comment]
Could someone with repository ownership/collaborator cancel these workflows? They are on an infinite loop.

**Pull request closed without merging**
