### PR TITLE
[MRG] fill empty files

### LINKED ISSUE #131: [BUG] empty files not allowed
Travis is failing with the following message:

```sh
1: [ERR] Empty files not allowed. (code: 99 - EMPTY_FILE)
		./sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.ds/BadChannels
		./sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.ds/bad.segments
```

also there is a warning:

```sh
	1: [WARN] Tabular file contains custom columns not described in a data dictionary (code: 82 - CUSTOM_COLUMN_WITHOUT_DESCRIPTION)
```

which needs to be fixed

### PR DESCRIPTION
**Pull request by sappelhoff**
closes #131 

I am attempting to solve it using a decorator, let's see if it works.

### CODE REVIEW

**Comment by jasmainak** [comment]
Looks like Travis is still not happy ...

**Comment by jasmainak** [comment]
@sappelhoff can you bring it back to `master` to make CIs happy?

let's start using the stable version when it's released. We should do the same for MNE. It's going to be released soon ...

**Comment by sappelhoff** [comment]
@jasmainak @teonbrooks please merge :-) ...  this will then fix #133, which can be merged directly after.

**Comment by jasmainak** [comment]
Thanks @sappelhoff !

**Pull request merged**
