### PR TITLE
MAINT: Report all unit test coverage

### PR DESCRIPTION
**Pull request by larsoner**
PR Description
--------------

Codecov should combine all coverage reports (it does for MNE I think?), so this conditional should (in principle!) be unnecessary. This should be useful for #406

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by larsoner** [comment]
Looks like the last `main` build had coverage of 94.53%. Hopefully this PR ends up >= that...

**Comment by larsoner** [comment]
Hah, +2 coverage!

**Comment by agramfort** [comment]
Thx @larsoner

**Comment by hoechenberger** [comment]
Niiiice!!

**Comment by sappelhoff** [comment]
I think I added that conditional at some point because I didn't want the CI to upload 10000 coverage reports :) ... but good to know that codecov deals with that internally

**Pull request merged**
