### PR TITLE
ENH: Add redirector

### PR DESCRIPTION
**Pull request by larsoner**

### CODE REVIEW

**Comment by larsoner** [comment]
Can only really work once it's in `main` so let's merge it and see if it works in PRs....

**Comment by sappelhoff** [comment]
@larsoner is this maybe a duplicate of https://github.com/mne-tools/mne-bids/blob/0bbd41433d56e3765fe0290b2fd94c6ddc71eaf1/.github/workflows/main.yml#L1

?

**Comment by larsoner** [comment]
Ohno! Yes it is. I'll revert mine then

**Comment by larsoner** [comment]
... actually I think I'd rather remove the `main.yml`. I think the `circleci_redirector.yml` is a better name actually.

**Comment by sappelhoff** [comment]
> ... actually I think I'd rather remove the main.yml. I think the circleci_redirector.yml is a better name actually.

agreed @larsoner

**Pull request merged**
