### PR TITLE
WIP: Modify extension matching for con and sqd

### PR DESCRIPTION
**Pull request by rob-luke**
PR Description
--------------

I think the kit copy file function was getting called regardless of the extension due to the modified function always being evaluated as true.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"
- [ ] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by agramfort** [comment]
nice catch.

the error is unrelated and due to a new release of check_manifest

@hoechenberger can you have look? thanks a lot

**Comment by sappelhoff** [comment]
thanks @rob-luke 

why did this pass our tests? should we add a check?

**Comment by hoechenberger** [comment]
@agramfort should work now, at least passes locally for me!

**Comment by agramfort** [comment]
thx @rob-luke @hoechenberger

**Pull request merged**
