### PR TITLE
converting .elp, .hsp files when calling `write_raw_bids` for KIT system

### PR DESCRIPTION
**Pull request by zuxfoucault**
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-bids/blob/master/CONTRIBUTING.md)

PR Description
--------------

Describe your PR here
Add scripts to convert .elp, .hsp files into bids format when calling `write_raw_bids` for KIT system
Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"
- [ ] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by agramfort** [comment]
@zuxfoucault can you add tests? thx

**Comment by jasmainak** [comment]
Just a thought, should we make a dedicated `copyfile_kit` function to keep the logic in one place? Thoughts @sappelhoff @agramfort ?

**Comment by jasmainak** [comment]
@zuxfoucault it's better to make pull requests from a feature branch than from `master`. You risk messing up your main copy if you do that + we cannot push to your fork to help

**Comment by agramfort** [comment]
+1 for a copyfile_kit function

**Comment by zuxfoucault** [comment]
> @zuxfoucault it's better to make pull requests from a feature branch than from `master`. You risk messing up your main copy if you do that + we cannot push to your fork to help

Thanks for pointing that out!
I will follow the convention. Just to clarify, so I better make PR from say my dev branch (zuxfoucault::dev) to the mne::master?

**Comment by jasmainak** [comment]
Fetch the latest branch from  mne-tools, "upstream" and make a new branch from that, push it to your fork "origin" and make a pull request from there. Use a separate branch for every PR

**Comment by jasmainak** [comment]
closing in favor of #323

**Pull request closed without merging**
