### PR TITLE
[BUG, WIP] Fix failing CIs

### PR DESCRIPTION
**Pull request by alexrockhill**
Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by alexrockhill** [comment]
Ok I switched to a new PR to fix the CIs but it seems that on top of the issue in https://github.com/mne-tools/mne-python/pull/9626, there is also a build/permissions issue

**Comment by agramfort** [comment]
@hoechenberger any idea?

**Comment by sappelhoff** [comment]
The issue might be:

```
npm
6.14.15
```

We need NPM v7 or higher for bids-validator now

**Comment by agramfort** [comment]
I think this PR fixed it no https://github.com/mne-tools/mne-bids/pull/870 ?

**Comment by sappelhoff** [comment]
> I think this PR fixed it no #870 ?

yes looks like it!

the esbuild thing is very new in bids-validator, it might cause headaches ... not sure. Anyhow, #870 looks good

**Comment by alexrockhill** [comment]
This is actually not the same as #870. See my comment there.

**Pull request closed without merging**
