### PR TITLE
[MRG] Start example for ds000117

### PR DESCRIPTION
**Pull request by jasmainak**
closes https://github.com/mne-tools/mne-bids/issues/7

### CODE REVIEW

**Comment by agramfort** [comment]
google doc on bids MEG format says that ds000117 is already in bids format on openfmri

at least there was this link provided:

http://openfmri.s3.amazonaws.com/tarballs/ds117_bids_emptyfiles.tgz

**Comment by jasmainak** [comment]
If I'm not mistaken, these are empty files. And this conversion was done manually ...

**Comment by agramfort** [comment]
yes but can you reuse what was done there?

**Comment by jasmainak** [comment]
okay, I could do with one round of reviews here. Feel free to clone and try the script. cc @teonbrooks and @choldgraf 

There is one problem at the moment. I don't seem to be getting the same event onsets as @jbwexler in [his PR on INCF](https://github.com/INCF/BIDS-examples/pull/27/files)

**Comment by choldgraf** [comment]
just fyi it'll be a bit of time before I can get to this, at the jupyter dev meeting now and have to do jupyter stuff for a few days...will loop back into neuro stuff after that. just letting you know I'm not leaving you hanging!

**Comment by jasmainak** [comment]
okay great!

**Comment by jasmainak** [comment]
Merged in master. Let's iterate directly on master

**Pull request closed without merging**
