### PR TITLE
[MAINT] speed up CIs through caching, bump up versions

### PR DESCRIPTION
**Pull request by sappelhoff**
this should speed up our CIs through caching pip ... and also the ds000117 data for building the docs.

edit, circleci speedup: from (before) 21:35 to (now) 11:31 minutes

Now that I have worked a lot with travis, circle, appveyor, and azure pipelines I have also find my favourite CI ... aaaand it's ... drummroll: CircleCI :-)

anyways, here is the rendering of updated docs (just the reference on top of the example): https://765-89170358-gh.circle-artifacts.com/0/html/auto_examples/convert_group_studies.html#sphx-glr-auto-examples-convert-group-studies-py

I also:
- bumped up the CI to test with MNE 0.18 and did some contingent code changes 
- made the data fetchers all save to  `~/mne_data/mne_bids_examples`

### CODE REVIEW

**Comment by jasmainak** [comment]
You have a Travis error

**Comment by jasmainak** [comment]
what is this file coverage.xml? why does this need to be committed?

**Comment by sappelhoff** [comment]
> what is this file coverage.xml? why does this need to be committed?

phew ... thanks for spotting it :-) `coverage.xml` is the pytest-cov report to be uploaded to codecov, it does NOT need to be committed (I added it to gitignore now)

**Comment by jasmainak** [comment]
Merged after squash. Thanks @sappelhoff !

**Pull request merged**
