### PR TITLE
MRG add osx in travis

### LINKED ISSUE #273: Enable CI testing on MAC
we have:
- circleci for building docs (running on linux)
- travis CI for testing (linux)
- appveyor for testing (windows)

We should search for which service allows us to test on MacOS as well.

### PR DESCRIPTION
**Pull request by agramfort**
closes #273

### CODE REVIEW

**Comment by jasmainak** [comment]
hmmm ... the windows error is the same as what @alexrockhill gets on his PR #237

**Comment by agramfort** [comment]
ok travis is green on mac too. But appveyor is red for some obscure reason. Can someone have a look? Shall we merge this as the appveyor failure is unrelated?

**Comment by agramfort** [comment]
👌

**Comment by jasmainak** [comment]
Thanks @agramfort !

**Pull request merged**
