### PR TITLE
[MRG] RF: Move functions related to Reading/Writing of electrodes/coordsystem sidecars to dig.py

### PR DESCRIPTION
**Pull request by adam2392**
PR Description
--------------

Addresses part 1 of: (https://github.com/mne-tools/mne-bids/pull/416#issuecomment-631868195)

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [x] All comments resolved
- [x] This is not your own PR
- [x] All CIs are happy
- [x] PR title starts with [MRG]
- <s>[ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated </s>
- [x] PR description includes phrase "closes <#issue-number>"
- [x] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by adam2392** [comment]
@agramfort this one should be reviewed first. This is the PR that @jasmainak requested be made to move existing code to a different file, making the diff smaller.

**Comment by hoechenberger** [comment]
Does this need a changelog entry? Otherwise LGTM

**Comment by jasmainak** [comment]
this is all private functions, so it's good. I'll go ahead and merge

**Comment by jasmainak** [comment]
Thanks @adam2392 . Can you now rebase and see if it improves the diff in your other PR?

**Pull request merged**
