### PR TITLE
[MRG] FIX: update check attribute as first thing in BIDSPath.update

### LINKED ISSUE #734: check argument works differently in BIDSPath.__init__() vs BIDSPath.update()
@adam2392 it seems #729 missed something in `BIDSPath.update()`:

```python
from mne_bids import BIDSPath

# good
p = BIDSPath(suffix='dataset_description', extension='.json', check=False)

# error
p = BIDSPath(extension='.json')
p.update(suffix='dataset_description', check=False)
```

### PR DESCRIPTION
**Pull request by sappelhoff**
closes #734 

cc @adam2392 @hoechenberger 

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [x] All comments resolved
- [x] This is not your own PR
- [x] All CIs are happy
- [x] PR title starts with [MRG]
- ~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated~
- [x] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by adam2392** [comment]
Crap, I accidentally pushed the fix to master. My bad. 

Also didn't see this PR.  :/

**Comment by agramfort** [comment]
I reverted 286c6e7a9658f29d3a50abb6c04cd0a988fb69ef in master

**Comment by adam2392** [comment]
@sappelhoff  if you update the unit test to be the following, then I think it covers our bases:

```Python
def test_datasetdescription_with_bidspath(return_bids_test_dir):
    with pytest.raises(ValueError, match='Unallowed'):
        bids_path = BIDSPath(
            root=return_bids_test_dir, suffix='dataset_description',
            extension='.json')

    # initialization should work
    bids_path = BIDSPath(
        root=return_bids_test_dir, suffix='dataset_description',
        extension='.json', check=False)
    assert bids_path.fpath.as_posix() == \
           Path(f'{return_bids_test_dir}/dataset_description.json').as_posix()

    # setting it via update should work
    bids_path = BIDSPath(root=return_bids_test_dir,
                         extension='.json', check=True)
    bids_path.update(suffix='dataset_description', check=False)
    assert bids_path.fpath.as_posix() == \
           Path(f'{return_bids_test_dir}/dataset_description.json').as_posix()
```

**Comment by sappelhoff** [comment]
> Crap, I accidentally pushed the fix to master. My bad.

been there, done that :-D it needs some time to adjust to new powers of pushing directly to upstream

**Pull request merged**
