### PR TITLE
try fix for docs (nirs example)

### PR DESCRIPTION
**Pull request by sappelhoff**

### CODE REVIEW

**Review by hoechenberger — COMMENTED** [review]
Shouldn't this fix go into MME-NIRS?

**Review by hoechenberger — COMMENTED** [review]
Shouldn't this fix go into MME-NIRS?

**Comment by sappelhoff** [comment]
That'd be even better, yes.

**Review by agramfort — APPROVED** [review]
Lets merge this until mne nirs is fixed.

**Comment by agramfort** [comment]
Lets make our CI green again 

cc @rob-luke in case you missed it

**Pull request merged**
