### PR TITLE
Fix Inspector tests for Matplotlib 3.6 compatibility

### LINKED ISSUE #1068: `key_press_event` is deprecated, needs to be replaced in our code
see: https://github.com/mne-tools/mne-bids/actions/runs/3145484445/jobs/5112832235#step:14:1665

### PR DESCRIPTION
**Pull request by hoechenberger**
Fixes #1068

Merge checklist
---------------

Maintainer, please confirm the following before merging.
If applicable:

- [ ] All comments are resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] New contributors have been added to [CITATION.cff](https://github.com/mne-tools/mne-bids/blob/main/CITATION.cff)
- [x] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by hoechenberger** [comment]
Failing tests must be fixed upstream in MNE.

**Comment by sappelhoff** [comment]
the doc build issue is due to https://github.com/mne-tools/mne-python/pull/11207

I'll try to push a fix here

**Review by sappelhoff — APPROVED** [review]

**Comment by sappelhoff** [comment]
@hoechenberger feel free to take out of draft status and merge when you are ready :-)

thanks for the fix

**Comment by hoechenberger** [comment]
I don't have time to work on the upstream changes. We can just leave this PR open until stuff gets fixed upstream, or we merge to already reduce the number of failing tests we see here. WDYT?

**Comment by sappelhoff** [comment]
merging, this is totally fine - thanks

**Pull request merged**
