### PR TITLE
[MRG] Adding `status_description` to channels.tsv files defaulting to n/a for now

### PR DESCRIPTION
**Pull request by adam2392**
PR Description
--------------

Closes: #348 

Defaults to `n/a` for now to allow for easy grepping as @jasmainak suggested. Future improvements can be made that allow the status to change, pending an addition to mne-python, or implementation of #458 

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [x] All comments resolved
- [x] This is not your own PR
- [x] All CIs are happy
- [x] PR title starts with [MRG]
- [x] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [x] PR description includes phrase "closes <#issue-number>"
- [x] Commit history does not contain any merge commits

### CODE REVIEW

**Comment by hoechenberger** [comment]
I missed the discussion in #348, but since I've started working on #491 I'm wondering why you would want to fill it with `n/a` instead of empty strings?That's what I'm doing in #491 and I feel that that's the "better" way, because … well I feel that this string field should be empty if there's no explicit value set …

**Comment by adam2392** [comment]
> I missed the discussion in #348, but since I've started working on #491 I'm wondering why you would want to fill it with `n/a` instead of empty strings?That's what I'm doing in #491 and I feel that that's the "better" way, because … well I feel that this string field should be empty if there's no explicit value set …

I think either value works, so can change it. That should pass the bids-validator right?

**Comment by hoechenberger** [comment]
> I think either value works, so can change it.

Let's see what the others think :)

> That should pass the bids-validator right?

Hah, thanks for the reminder. I forgot to include BIDS validation in #491. Let's see…

**Comment by hoechenberger** [comment]
> Hah, thanks for the reminder. I forgot to include BIDS validation in #491. Let's see…

Ok so this is resolved now… won't pass the validation with an empty cell, so I'm using `n/a` now in #491 too as a default! :)

**Comment by hoechenberger** [comment]
@sappelhoff Feel free to merge if you're happy

**Comment by agramfort** [comment]
+0 on my side. I did not follow discussion.

@sappelhoff @jasmainak ball is in your hands

**Comment by sappelhoff** [comment]
thanks @adam2392

**Pull request merged**
