### PR TITLE
MRG: Various doc improvements

### PR DESCRIPTION
**Pull request by hoechenberger**
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-bids/blob/main/CONTRIBUTING.md)

PR Description
--------------

Describe your PR here

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
looks like a good idea to me. Can you think of some "docs" we can link to here and also in MNE-Python, so that "path-like" shows up as a link, instead of just in cursive font in the API docs (see screenshot right below)

image


For example `file-like` links to `python:file object` in MNE-Python

see: https://github.com/mne-tools/mne-python/blob/a2ab1e25fde473dc1e47dcc83e4426ce60397461/doc/conf.py#L171-L173

**Comment by hoechenberger** [comment]
I guess I'll add this to MNE's glossary and we can then link to it

**Comment by sappelhoff** [comment]
> I guess I'll add this to MNE's glossary and we can then link to it

good idea! And thanks a lot

**Review by agramfort — APPROVED** [review]
+1 for MRG when green

🙏 @hoechenberger

**Comment by hoechenberger** [comment]
Upstream PR: https://github.com/mne-tools/mne-python/pull/10003

**Comment by hoechenberger** [comment]
- Added alias from `mne_bids.BIDSPath` to `BIDSPath` and replaced the occurrences of the former with the latter in the API docs parameter type descriptions
- Added aliases with links for `int`, `float`, `list`, `tuple` (links to Python docs)
- Added alias / link from `path-like` to MNE-Python glossary; this link won't function (and, consequently, the doc build will throw errors) until https://github.com/mne-tools/mne-python/pull/10003 has been merged, the docs been rebuilt, and deployed

**Review by sappelhoff — COMMENTED** [review]
does this work locally? I can't really see why CircleCI is complaining :confounded:

**Comment by hoechenberger** [comment]
Yes it worked locally … I just changed something, let's see if that fixes it

**Pull request merged**
