### PR TITLE
bump cache, install with deps

### PR DESCRIPTION
**Pull request by sappelhoff**
See:

- https://github.com/mne-tools/mne-python/pull/10261#issuecomment-1025174845

### CODE REVIEW

**Comment by sappelhoff** [comment]
probably the fix here is rather than installing mne[hdf5], to update mne-bids dependencies to optionally include pymatreader when EEGLAB operations are wanted, WDYT?

cc @hoechenberger

**Review by agramfort — APPROVED** [review]
nice catch !

**Comment by agramfort** [comment]
@hoechenberger I let you merge if happy

**Comment by hoechenberger** [comment]
Thanks @sappelhoff!

**Pull request merged**
