### PR TITLE
Add support for new EEGLAB format

### LINKED ISSUE #761: new EEGLAB files may contain fields in root of file, instead of nested in "EEG" struct
see: https://github.com/mne-tools/mne-python/pull/8874

We need to apply @cbrnr's fix also here:

https://github.com/mne-tools/mne-bids/blob/415988e88f6253527d38d60dd521d0b94d5baa98/mne_bids/copyfiles.py#L516-L518

### PR DESCRIPTION
**Pull request by cbrnr**
Add support for new EEGLAB format (data is not contained inside `EEG` struct anymore). Fixes #761.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [x] All comments resolved
- [x] This is not your own PR
- [x] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [x] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by cbrnr** [comment]
Let me know what kind of test you would like to add.

**Comment by sappelhoff** [comment]
great, thanks! Could you add a test similar to the one that we have, but using the new EEGLAB data file you added to the mne testing data in https://github.com/mne-tools/mne-python/pull/8874 ?

Although that **does** remind me of https://github.com/mne-tools/mne-bids/issues/654 and I hope we won't run into problems with that.

Actually, there is also https://github.com/jackz314/eeglabio out there now ... which may even be another option.

**Comment by cbrnr** [comment]
Can we upgrade to MNE 0.23? I need the new test file...

**Comment by sappelhoff** [comment]
Yes from my side, objections @hoechenberger ?

**Comment by cbrnr** [comment]
Also, if we can live with `preload=True` in the test I could get rid of that extra `if` condition.

**Comment by sappelhoff** [comment]
I'd say just go ahead, I don't think there'll be many objections as long as testing time doesn't explode (which it probably won't).

And we'll want to require mne 0.23 for mne-bids-dev at some point anyhow, so might as well start now.

**Comment by cbrnr** [comment]
OK! Let me know once 0.23 is available!

**Comment by hoechenberger** [comment]
Hello! Can we revive this one? 💪

**Comment by sappelhoff** [comment]
> Hello! Can we revive this one?

probably once #797 is merged? Looks all green to me, that one.

**Comment by cbrnr** [comment]
All green!

**Review by sappelhoff — APPROVED** [review]
Thanks @cbrnr !

**Pull request merged**
