### PR TITLE
MRG, BUG: _find_matching_sidecar requires optional coordinate.json in EEG & MEG data

### PR DESCRIPTION
**Pull request by dieloz**
PR Description
--------------
When reading eeg-bids data that contain template electrodes, not the [digitized ones](https://mne.tools/mne-bids/stable/auto_examples/convert_eeg_to_bids.html?highlight=coordsystem%20json) I got the following error:
```
Reading /home/diego/Downloads/course_eeg_WS2020-main/data/P3BIDS/sub-001/eeg/sub-001_task-P3_eeg.fdt
Reading events from /home/diego/Downloads/course_eeg_WS2020-main/data/P3BIDS/sub-001/eeg/sub-001_task-P3_events.tsv.
Reading channel info from /home/diego/Downloads/course_eeg_WS2020-main/data/P3BIDS/sub-001/eeg/sub-001_task-P3_channels.tsv.
<ipython-input-4-ae69afb69ac1>:26: RuntimeWarning: Did not find any coordsystem.json associated with sub-001_task-P3.
The search_str was "/home/diego/Downloads/course_eeg_WS2020-main/data/P3BIDS/sub-001/**/sub-001*coordsystem.json"
  raw = read_raw_bids(bids_path)
```
The error is produced because the **_find_matching_sidecar** subfunction in read.py [L521](https://github.com/mne-tools/mne-bids/blob/42aa7f5b86a91055c70bb3d4c4fbc31c45488203/mne_bids/read.py#L521) on_error is 'warn' because the suffix  is **eeg**

The code I used to produce the error is the following:

```
import mne, mne_bids, pathlib

#Load the data
from mne_bids import (BIDSPath, read_raw_bids,
                      print_dir_tree, make_report, update_sidecar_json)

#path where to save the datasets.
bids_root = pathlib.Path('/home/diego/Downloads/course_eeg_WS2020-main/data/P3BIDS')
subject_id = '001' # recommend subject 2 for now

bids_path = BIDSPath(subject=subject_id, task='P3',
                     suffix='eeg', extension='.set',
                     root=bids_root)
#read the file
raw = read_raw_bids(bids_path)
```
The eeg dataset I used is freely available (https://osf.io/etdkz/) and successfully validated using the **https://bids-standard.github.io/bids-validator/**

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Review by sappelhoff — APPROVED** [review]
indeed, your fix looks good to me, thanks a lot!

For EEG files, coords JSON and electrods TSV are entirely optional. --> however, coords JSON becomes mandatory as soon as electrodes TSV is found.

please check and merge if you are happy @adam2392 @hoechenberger

**Comment by hoechenberger** [comment]
Looking good to me! @dieloz could you add a bugfix entry to the changelog to get credit for this fix?

Our CI is really flaky, we should do something about this…

**Comment by adam2392** [comment]
Is coords mandatory for Meg tho? I have trouble keeping track of what's required :p. 

+1 for eeg and IEEG tho

**Comment by sappelhoff** [comment]
> Is coords mandatory for Meg tho? I have trouble keeping track of what's required :p.

optional for MEG

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#coordinate-system-json-_coordsystemjson

**Comment by dieloz** [comment]
> changelog
Thank you very much @hoechenberger @adam2392 @sappelhoff and @arokem.
Regarding the changelog, I found this {here](https://mne.tools/stable/install/contributing.html#describe-your-changes-in-the-changelog) is this what I should do? Sorry I'm python and mne noob

Bug
---

.. |Diego Lozano-Soldevilla| replace:: **Diego Lozano-Soldevilla**

- Short description of the changes (:gh:`0000` **by new contributor** |Diego Lozano-Soldevilla|_)
In the current state, *_find_matching_sidecar* (read.py subfunction) asumes all eeg datasets will contain electrode/coordsystem.json files. The error is produced because the  L521 on_error is 'warn' because the suffix is eeg

> Looking good to me! @dieloz could you add a bugfix entry to the changelog to get credit for this fix?
> 
> Our CI is really flaky, we should do something about this…

**Comment by hoechenberger** [comment]
@dieloz I've added a changelog entry for you.

I think we can merge once CI goes green.

**Review by hoechenberger — APPROVED** [review]

**Review by sappelhoff — APPROVED** [review]

**Comment by dieloz** [comment]
Thank you very much @hoechenberger !

**Comment by sappelhoff** [comment]
and thanks @dieloz

**Comment by dieloz** [comment]
Very glad to contribute! Thanks to you all for creating and maintaining this wonderful project! Very eager to learn more and hopefully keep contributing ;)

**Pull request merged**
