### PR TITLE
[MRG] appveyor for windows

### PR DESCRIPTION
**Pull request by jasmainak**

### CODE REVIEW

**Comment by jasmainak** [comment]
okay, we have this set up now. "Just" need to fix the failures ...

**Comment by agramfort** [comment]
it's just an engineering problem it should be easy :)

**Comment by jasmainak** [comment]
@agramfort I'm bluffed. When I do `which bids-validator` it seems to work and it's added to the path. But it doesn't seem to work when called from `mne.utils.run_subprocess`. I get "command not found". Any clue?

**Comment by agramfort** [comment]
Can you replicate with a windows VM?
You can also log via Remote Desktop on an appveyor machine for interactive debugging

**Comment by jasmainak** [comment]
Hooray !!!! finally :beers:

**Comment by jasmainak** [comment]
Thanks for the review @agramfort !

**Pull request merged**
