### PR TITLE
[MRG] update function to raw_to_bids

### PR DESCRIPTION
**Pull request by teonbrooks**

### CODE REVIEW

**Comment by jasmainak** [comment]
@teonbrooks can you update one example so I can try it?

**Comment by teonbrooks** [comment]
ready for review

**Comment by jasmainak** [comment]
@teonbrooks have you given up on pep8? ;P

never mind, I'll make a cleanup commit and merge :)

**Comment by jasmainak** [comment]
Merged. Thanks @teonbrooks

**Comment by choldgraf** [comment]
lol this was a hilarious final few moments of this pr

**Comment by teonbrooks** [comment]
> @teonbrooks have you given up on pep8? ;P

wait? what pep8 errors?! I only write beautiful code!

**Comment by teonbrooks** [comment]
upon further review, maybe I need to properly configure my linter ;) also, we should have ci for it!

**Comment by jasmainak** [comment]
> maybe I need to properly configure my linter ;)

or maybe start using Sublime text instead of fancy-pants Atom :P

**Comment by agramfort** [comment]
> or maybe start using Sublime text instead of fancy-pants Atom :P

+1

**Pull request merged**
