### PR TITLE
[MRG] CI/Maint: speed up circleci builds with machine executor

### PR DESCRIPTION
**Pull request by sappelhoff**
See my short description in https://github.com/mne-tools/mne-python/issues/10006#issuecomment-975421020

This should significantly speed up our doc builds with CircleCI. Just "nice to have".

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by hoechenberger** [comment]
Nice! Let's see if this changes anything

**Comment by sappelhoff** [comment]
Seems like disregarding caching, this is about a 2 minute speed up :laughing: so not really significant, but it's been worth these 5 minutes of my time :-)

also fixed a link.

old: https://app.circleci.com/pipelines/github/mne-tools/mne-bids/3622/workflows/695a9fed-0095-4c97-9963-e75af09ce60f/jobs/5636

new (disregard the cachine, which was not needed in "old"): https://app.circleci.com/pipelines/github/mne-tools/mne-bids/3625/workflows/b5b298d9-d650-4bf9-9750-cad505dd0ba4/jobs/5639

**Comment by sappelhoff** [comment]
okay, with the caches having been refreshed, the new build (after the link fix commit above) is actually super fast :tada:

**Comment by hoechenberger** [comment]
Thanks @sappelhoff!

**Pull request merged**
